unpackaged/main/default/objects/Clip__c/Clip__c.object-meta.xml
<CustomObject>
    <label>Clip</label>
    <nameField>
        <label>Clip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clip_Relation__c/Clip_Relation__c.object-meta.xml
<CustomObject>
    <label>Clip Relation</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Clip Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clip Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clip_Relation__c/fields/Clip__c.field-meta.xml
<CustomField>
    <fullName>Clip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clip</label>
    <referenceTo>Clip__c</referenceTo>
    <relationshipLabel>Clip Relations</relationshipLabel>
    <relationshipName>Clip_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clip_Relation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clip_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Notification__c/Navatar_Notification__c.object-meta.xml
<CustomObject>
    <label>Navatar Notification</label>
    <nameField>
        <displayFormat>NN-{000000}</displayFormat>
        <label>Navatar Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Notification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add Note</fullName>
            </value>
            <value>
                <fullName>Add Tag</fullName>
            </value>
            <value>
                <fullName>Clip Info</fullName>
            </value>
            <value>
                <fullName>Account Info</fullName>
            </value>
            <value>
                <fullName>Deal Activity Info</fullName>
            </value>
            <value>
                <fullName>Theme Activity Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Navatar_Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Navatar_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/NavatarClipRelationHandler.cls
/************************************************************************************
** Module Name : Clip Relation Trigger Handler
** Description : This class is used for handling clip relation insert
** Class: ClipRelationTriggerHandler
** Organization : Navatar Group
** Revision History:-
** Version Date(YYYY-MM-DD)    Author                  
** 1.0     2022-11-25          Adil Aleem   
** 2.0     2023-02-23          Pavani         Created the clipRelationTrigger with new name
****************************************************************************************************************/
public with sharing class NavatarClipRelationHandler {
     /*****************************************************************************************************
    * @Name         :   onAfterInsert
    * @Description  :   Method to handle after update of Clip Relation
    * @Parameter    :   Map<Id , Clip_Relation__c>
    *****************************************************************************************************/
    public static void onAfterInsert(Map<Id , Clip_Relation__c> newRecordMap){
        Map<String , Boolean> notificationSettings = NavatarUtility.isNotificationAllowed();
        if(notificationSettings.containsKey('info') && notificationSettings.get('info')){
            createInfoNotification(newRecordMap);
        }     
    }

     /*****************************************************************************************************
    * @Name         :   createInfoNotification
    * @Description  :   Method to create Info Notification record based on creation of Clip Relation
    * @Parameter    :   Map<Id , Clip_Relation__c>
    *****************************************************************************************************/
    private static void createInfoNotification(Map<Id , Clip_Relation__c> newRecordMap){
        Set<String> existingNotificationSet = new Set<String>();
        List<Navatar_Notification__c> notificationList = new List<Navatar_Notification__c>(); 
        //added  stripInaccessible by Pavani w.r.t security fix 
        for(SObject notif :Security.stripInaccessible(AccessType.READABLE,
                            [SELECT Id, Record_ID__c, User__c, Type__c 
                            FROM Navatar_Notification__c 
                            WHERE Record_ID__c IN :newRecordMap.keySet()]).getRecords()){
            Navatar_Notification__c nn = (Navatar_Notification__c)notif;
            if(nn.isSet('Record_ID__c') && nn.Record_ID__c != null && nn.isSet('User__c') && nn.User__c != null) {
                existingNotificationSet.add(nn.Record_ID__c + '-' + nn.User__c + '-' + nn.Type__c);
            }   
        }

        for(Clip_Relation__c cr : newRecordMap.values()){ 
            //added FLS check on Clip by Pavani w.r.t security fix
            if(Schema.sObjectType.Clip_Relation__c.fields.User__c.isAccessible() && 
                Schema.sObjectType.Clip_Relation__c.fields.Clip__c.isAccessible()){
            String key = cr.Clip__c + '-' + cr.User__c + '-' + NavatarConstants.CLIP_INFO;
            if(!existingNotificationSet.contains(key) && cr.User__c != userinfo.getUserId()){
                Navatar_Notification__c nn = new Navatar_Notification__c();  
                if (Schema.sObjectType.Navatar_Notification__c.fields.Record_ID__c.isCreateable()) {
                    nn.Record_ID__c = cr.Clip__c;
                }
                if (Schema.sObjectType.Navatar_Notification__c.fields.User__c.isCreateable()) {
                    nn.User__c = cr.User__c;
                }
                if (Schema.sObjectType.Navatar_Notification__c.fields.Type__c.isCreateable()) {
                    nn.Type__c = NavatarConstants.CLIP_INFO;
                }
                notificationList.add(nn);         
            }
        } 
        } 
             
        if(!notificationList.isEmpty() && Schema.getGlobalDescribe().get('navpeII_dev18__Navatar_Notification__c').getDescribe().isCreateable()){
            Database.insert(notificationList , false);
        }    
    }
}