unpackaged/main/default/objects/DPInfo__c/DPInfo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DPInfo</label>
</CustomObject>

unpackaged/main/default/objects/DPInfo__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/User_Identifier__c.field-meta.xml
<CustomField>
    <fullName>User_Identifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/Cls_DealPortalInfo.cls
public with sharing class Cls_DealPortalInfo 
{
   
 public List<User> allUser;
 public DPInfo__c dpInfo{get; set;}
 public String info{get; set;}
 
 public Cls_DealPortalInfo()
 { 
   allUser = new List<User>();
   if(Schema.sObjectType.User.isAccessible() &&  Schema.sObjectType.User.fields.User_Identifier__c.isAccessible())
        allUser=[select id,User_Identifier__c from User where id=:userInfo.getUserId() Limit 1];
   if(allUser.size()>0 && allUser!=null && allUser[0].User_Identifier__c!=null && allUser[0].User_Identifier__c!='')
   {
        dpInfo=DPInfo__c.getValues(allUser[0].User_Identifier__c); 
        if(dpInfo!=null)
        {
            info=dpInfo.Info__c;
        }
        
   }   
 }
 
  public void deleteInfo() 
  {
   if(dpInfo!=null && Schema.sObjectType.DPInfo__c.isDeletable())
       delete dpInfo;
   info=null;
  }

//    Test Method

public static testMethod void testDealPortalInfo()
{
  Cls_DealPortalInfo testDeal=new Cls_DealPortalInfo();
  System.assertnotEquals(2,testDeal.allUser.size());
  testDeal.deleteInfo();
}


 
}