unpackaged/main/default/objects/Account/fields/AUM_in_Millions__c.field-meta.xml
<CustomField>
    <fullName>AUM_in_Millions__c</fullName>
    <label>AUM (in Millions)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Date Created</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Familiar_Name__c.field-meta.xml
<CustomField>
    <fullName>Familiar_Name__c</fullName>
    <description>Nick name for Institution</description>
    <label>Familiar Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <label>Location Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australasia</fullName>
            </value>
            <value>
                <fullName>Caribbean</fullName>
            </value>
            <value>
                <fullName>Central and East Europe</fullName>
            </value>
            <value>
                <fullName>Emerging Markets</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Far East</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>South Asia</fullName>
            </value>
            <value>
                <fullName>West Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Candidate_Role__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Role__c</fullName>
    <label>Candidate Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Note for Admin- Please do not change these picklist values, since it may impact certain features of Navatar Deal Connect.</description>
    <inlineHelpText>Note for Admin- Please do not change these picklist values, since it may impact certain features of Navatar Deal Connect.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Navatar Deal Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/Navatar_Setup__c.object-meta.xml
<CustomObject>
    <label>Navatar Setup</label>
    <nameField>
        <displayFormat>NS - {0000000000}</displayFormat>
        <label>Navatar Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/fields/Admin_Setting__c.field-meta.xml
<CustomField>
    <fullName>Admin_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Setting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS__c.field-meta.xml
<CustomField>
    <fullName>DCS__c</fullName>
    <label>DCS</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS_New_Company__c.field-meta.xml
<CustomField>
    <fullName>DCS_New_Company__c</fullName>
    <label>DCS New Company</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS_New_Source_Contact__c.field-meta.xml
<CustomField>
    <fullName>DCS_New_Source_Contact__c</fullName>
    <label>DCS New Source Contact</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS_New_Source_Firm__c.field-meta.xml
<CustomField>
    <fullName>DCS_New_Source_Firm__c</fullName>
    <label>DCS New Source Firm</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Pipeline__c/Pipeline__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pipeline__c/fields/EBIT__c.field-meta.xml
<CustomField>
    <fullName>EBIT__c</fullName>
    <label>EBIT</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pipeline__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Internal Relationship</fullName>
            </value>
            <value>
                <fullName>Internal Idea Generation</fullName>
            </value>
            <value>
                <fullName>Executive Board/Management Affiliate</fullName>
            </value>
            <value>
                <fullName>Other Financial Sponsor</fullName>
            </value>
            <value>
                <fullName>Navatar Deal Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pipeline__c/fields/Source_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Name__c</fullName>
    <label>Source Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pipeline__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Received</fullName>
            </value>
            <value>
                <fullName>NDA Signed</fullName>
            </value>
            <value>
                <fullName>Management Meeting</fullName>
            </value>
            <value>
                <fullName>IOI</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Declined/Dead</fullName>
            </value>
            <value>
                <fullName>Parked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Test_Deal_Creation_Ctlr.cls
@isTest
public class Test_Deal_Creation_Ctlr{
    static String sCompanyApi =  CommonUtility.chkmasterLookupInPiplineAPI();

    public static testMethod void Test_DealCreation() {
        
    try {
            System.currentPageReference().getParameters().put('retURL', 'lightning/page/home');
            string np = CommonUtility.strNameSpacePrefix; 
            String strRecordTypeId = [Select Id ,developername From RecordType Where SobjectType = 'Account' and developername = 'Company'].Id;
             
            Navatar_Setup__c navSetup= new Navatar_Setup__c();            
            navSetup.admin_setting__c    =  true;
            navSetup.dcs__c = 'account:accountsource,account:'+np+'aum_in_millions__c,'+np+'pipeline__c:'+np+'source_name__c,account:'+np+'bank_account_number__c;account:'+np+'date_created__c,'+np+'pipeline__c:'+np+'ebit__c,Contact:LastName';
            navSetup.dcs_new_company__c = ''+strRecordTypeId+'';
            navSetup.dcs_new_source_contact__c = 'contact:'+np+'candidate_role__c,contact:'+np+'testdatefield__c,contact:'+np+'fees__c';
            insert navSetup;
                        
            String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' And Name = 'Limited Partner'].Id;
        
            Account parentAccount = new Account();
            parentAccount.Name = 'SunMicro Group';
            insert parentAccount;
            
            Account acc = new Account();
            acc.Name = 'AIS Group';
            //acc.RecordTypeId = recdTypeId;
            acc.ParentId = parentAccount.id;
            insert acc; 
            
            Pipeline__c objPipeline = new Pipeline__c();
            objPipeline.name = 'PipeLine';           
            objPipeline.put(sCompanyApi, acc.id);
            objPipeline.Stage__c = 'LOI';
            objPipeline.Source__c = 'Bank';            
            insert objPipeline;
            
            Deal_Creation_Ctlr dclSetup= new  Deal_Creation_Ctlr();
            Deal_Creation_Ctlr.objectfield objWarp = new Deal_Creation_Ctlr.objectfield();
            dclSetup.openSourceFirmPopup();
           // dclSetup.showMessage();
            dclSetup.openSourceContactPopup();
            dclSetup.strRequiredField = 'Account:Name,Pipeline__c:Name,Pipeline__c:'+ sCompanyApi +',Pipeline__c:Stage__c';
            dclSetup.strSourcePopupReqField = 'Account:Name,Account:Familiar_Name__c,Contact:LastName';
            dclSetup.viewRequiredFieldonPage();
            dclSetup.onCancel();        
            Deal_Creation_Ctlr.getRecorTypeid();
            dclSetup.CreateDeal();
            System.assertEquals('PipeLine',objPipeline.Name);
        } catch (Exception e) {
            //System.assert(false, 'Exception ' + e);
        }
    }    
    
    public static testMethod void Test_DealCreation2() {
        
    try {
            System.currentPageReference().getParameters().put('retURL', 'lightning/page/home');
            string np = CommonUtility.strNameSpacePrefix; 
            String strRecordTypeId = [Select Id ,developername From RecordType Where SobjectType = 'Account' and developername = 'Company'].Id;
             
            Navatar_Setup__c navSetup= new Navatar_Setup__c();
            
            navSetup.admin_setting__c    =  true;           
            navSetup.dcs_new_source_contact__c = 'Source Contact: Source Contact2: Source Contact3';
            navSetup.dcs_new_source_firm__c = '1234;account:accountsource,account:'+np+'locations__c,account:'+np+'bank_account_number__c';
            navSetup.dcs_new_company__c = '12312';
            navSetup.dcs__c = 'account:accountsource,'+np+'pipeline__c:'+np+'source_name__c,account:'+np+'aum_in_millions__c,account:'+np+'bank_account_number__c;account:'+np+'date_created__c,'+np+'pipeline__c:'+np+'ebit__c,Contact:LastName';
           
            navSetup.dcs_new_company__c = ''+strRecordTypeId+'';
            navSetup.dcs_new_source_contact__c = 'contact:'+np+'candidate_role__c,contact:'+np+'testdatefield__c,contact:'+np+'fees__c';
            insert navSetup;
                        
            String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' And Name = 'Limited Partner'].Id;
        
            Account acc = new Account();
            acc.name = 'SunMicro Group';
            acc.bank_account_number__c = 'test';            
            insert acc;
                        
            Pipeline__c objPipeline = new Pipeline__c();
            objPipeline.name = 'PipeLine';           
            objPipeline.put(sCompanyApi, acc.id);
            objPipeline.Stage__c = 'LOI';
            objPipeline.Source__c = 'Bank';            
            insert objPipeline;
            
            Contact cont= new Contact();
            cont.firstname = 'john';
            cont.lastname = 'smith';
            cont.accountid = acc.id;            
            insert cont;
            
            Deal_Creation_Ctlr dclSetup= new  Deal_Creation_Ctlr();
            Deal_Creation_Ctlr.objectfield objWarp = new Deal_Creation_Ctlr.objectfield();
            dclSetup.openSourceFirmPopup();
           // dclSetup.showMessage();
            dclSetup.objSourceAccount = acc;
            dclSetup.objSourceContact = cont;
            dclSetup.strSourceFirmName = 'test';
            dclSetup.strSourceContactName = 'test1';
            dclSetup.openSourceContactPopup();
            dclSetup.strRequiredField = 'Account:Name,Pipeline__c:Name,Pipeline__c:' + sCompanyApi + ',Pipeline__c:Stage__c';
            dclSetup.strSourcePopupReqField = 'Account:Name,Account:Familiar_Name__c,Contact:LastName';
            dclSetup.viewRequiredFieldonPage();
            dclSetup.onCancel();        
            Deal_Creation_Ctlr.getRecorTypeid();
            
            dclSetup.CreateDeal();
            System.assertEquals('PipeLine',objPipeline.Name);
        } catch (Exception e) {
           // System.assert(false, 'Exception ' + e);
        }
    }    
   
}