unpackaged/main/default/objects/Account/fields/AUM_in_Millions__c.field-meta.xml
<CustomField>
    <fullName>AUM_in_Millions__c</fullName>
    <label>AUM (in Millions)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Date Created</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <label>Location Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australasia</fullName>
            </value>
            <value>
                <fullName>Caribbean</fullName>
            </value>
            <value>
                <fullName>Central and East Europe</fullName>
            </value>
            <value>
                <fullName>Emerging Markets</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Far East</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>South Asia</fullName>
            </value>
            <value>
                <fullName>West Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Candidate_Role__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Role__c</fullName>
    <label>Candidate Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/Navatar_Setup__c.object-meta.xml
<CustomObject>
    <label>Navatar Setup</label>
    <nameField>
        <displayFormat>NS - {0000000000}</displayFormat>
        <label>Navatar Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/fields/Admin_Setting__c.field-meta.xml
<CustomField>
    <fullName>Admin_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Setting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS__c.field-meta.xml
<CustomField>
    <fullName>DCS__c</fullName>
    <label>DCS</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS_New_Company__c.field-meta.xml
<CustomField>
    <fullName>DCS_New_Company__c</fullName>
    <label>DCS New Company</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS_New_Source_Contact__c.field-meta.xml
<CustomField>
    <fullName>DCS_New_Source_Contact__c</fullName>
    <label>DCS New Source Contact</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/DCS_New_Source_Firm__c.field-meta.xml
<CustomField>
    <fullName>DCS_New_Source_Firm__c</fullName>
    <label>DCS New Source Firm</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Pipeline__c/Pipeline__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pipeline__c/fields/EBIT__c.field-meta.xml
<CustomField>
    <fullName>EBIT__c</fullName>
    <label>EBIT</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Test_Deal_Creation_Setup_Ctlr.cls
@isTest
public class Test_Deal_Creation_Setup_Ctlr{
    public static testMethod void Test_DealCreationSetup() {
        
    try {
            string np = CommonUtility.strNameSpacePrefix; 
            String strRecordTypeId = [Select Id ,developername From RecordType Where SobjectType = 'Account' and developername = 'Company'].Id;
            
            Navatar_Setup__c navSetup= new Navatar_Setup__c();           
            navSetup.admin_setting__c    =  true;
            navSetup.DCS_New_Source_Contact__c = 'Source Contact: Source Contact2: Source Contact3';
            navSetup.DCS_New_Source_Firm__c = '01236000000QfDmAAK;account:accountsource,account:'+np+'locations__c,account:'+np+'bank_account_number__c';
            navSetup.dcs_new_company__c = 'New Company';
            navSetup.DCS__c = 'account:accountsource,account:'+np+'aum_in_millions__c,account:'+np+'bank_account_number__c;account:'+np+'date_created__c,'+np+'pipeline__c:'+np+'ebit__c,Contact:LastName';
            navSetup.dcs__c = 'account:accountsource,account:'+np+'aum_in_millions__c,account:'+np+'bank_account_number__c;account:'+np+'date_created__c,'+np+'pipeline__c:'+np+'ebit__c,account:'+np+'test_date_time__c';
            
            navSetup.dcs_new_company__c = ''+strRecordTypeId+'';
            navSetup.dcs_new_source_firm__c = ''+strRecordTypeId+';account:parentid';
            navSetup.dcs_new_source_contact__c = 'contact:'+np+'candidate_role__c,contact:'+np+'testdatefield__c,contact:'+np+'fees__c';
            insert navSetup;
                        
            Deal_Creation_Setup_Ctlr dclSetup= new  Deal_Creation_Setup_Ctlr();
            dclSetup.getRecordType();
            dclSetup.strFieldApiName = 'account:accountnumber;account:accountsource<@>'+strRecordTypeId+';account:accountnumber<@>contact:description<@>'+strRecordTypeId+'';
            dclSetup.setRecordType();
            dclSetup.onclickSaveButton();
            dclSetup.onCancel();
            dclSetup.onRevertToDefault();
            dclSetup.fetchEditSectionValue();
            
        } catch (Exception e) {
            System.assert(false, 'Exception ' + e);
        }
    }
    
    public static testMethod void Test_DealCreationSetup2() {
        
    try {
            string np = CommonUtility.strNameSpacePrefix; 
            String strRecordTypeId = [Select Id ,developername From RecordType Where SobjectType = 'Account' and developername = 'Company'].Id;
            
            Navatar_Setup__c navSetup= new Navatar_Setup__c();           
            navSetup.admin_setting__c    =  true;
            navSetup.DCS_New_Source_Contact__c = 'Source Contact: Source Contact2: Source Contact3';
            navSetup.DCS_New_Source_Firm__c = ''+strRecordTypeId+';account:accountsource,account:'+np+'locations__c,account:'+np+'bank_account_number__c';
            navSetup.dcs_new_company__c = 'New Company';
            navSetup.dcs__c = 'account:accountsource,account:'+np+'aum_in_millions__c,account:'+np+'bank_account_number__c;account:'+np+'date_created__c,'+np+'pipeline__c:'+np+'ebit__c,account:'+np+'test_date_time__c';
            insert navSetup;
                        
            Deal_Creation_Setup_Ctlr dclSetup= new  Deal_Creation_Setup_Ctlr();
            dclSetup.getRecordType();
            dclSetup.strFieldApiName = 'account:accountnumber;account:accountsource<@>'+strRecordTypeId+';account:accountnumber<@>contact:description<@>'+strRecordTypeId+'';
            dclSetup.setRecordType();
            dclSetup.onclickSaveButton();
            dclSetup.onCancel();
            dclSetup.onRevertToDefault();
            dclSetup.fetchEditSectionValue();
            
        } catch (Exception e) {
            System.assert(false, 'Exception ' + e);
        }
    }
 
}