unpackaged/main/default/objects/Account/fields/Closing_Data_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Data_Date__c</fullName>
    <label>Closing Data Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Geographic_Region__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Region__c</fullName>
    <description>Note for Admin- Please do not change these picklist values, since it may impact certain features of Navatar Deal Connect.</description>
    <inlineHelpText>Note for Admin- Please do not change these picklist values, since it may impact certain features of Navatar Deal Connect.</inlineHelpText>
    <label>Geographic Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Central America</fullName>
            </value>
            <value>
                <fullName>Caribbean</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/LimitedPartner.recordType-meta.xml
<RecordType>
    <fullName>LimitedPartner</fullName>
    <active>true</active>
    <description>A Limited Partner is the legal entity that the Investor uses to invest in your funds. Each Limited Partner entity has to be linked to an Institution.</description>
    <label>Limited Partner</label>
</RecordType>

unpackaged/main/default/objects/Commitment__c/Commitment__c.object-meta.xml
<CustomObject>
    <label>Commitment</label>
    <nameField>
        <displayFormat>CMT - {000000}</displayFormat>
        <label>Commitment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commitment__c/fields/AllowChange__c.field-meta.xml
<CustomField>
    <fullName>AllowChange__c</fullName>
    <defaultValue>true</defaultValue>
    <label>AllowChange</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Has_Child__c.field-meta.xml
<CustomField>
    <fullName>Has_Child__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Child</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/KYC__c.field-meta.xml
<CustomField>
    <fullName>KYC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>KYC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LP</fullName>
            </value>
            <value>
                <fullName>GP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <referenceTo>Partnership__c</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Tax_Forms__c.field-meta.xml
<CustomField>
    <fullName>Tax_Forms__c</fullName>
    <label>Tax Forms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>W-8BEN</fullName>
            </value>
            <value>
                <fullName>W-8IMY</fullName>
            </value>
            <value>
                <fullName>W-9</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Total_Commitments__c.field-meta.xml
<CustomField>
    <fullName>Total_Commitments__c</fullName>
    <label>Total Commitments</label>
    <summarizedField>Partnership__c.Total_Commitments__c</summarizedField>
    <summaryForeignKey>Partnership__c.Fund__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/Fundraising__c.object-meta.xml
<CustomObject>
    <label>Fundraising</label>
    <nameField>
        <label>Fundraising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraisings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Investment_Likely_Amount_USD_mn__c.field-meta.xml
<CustomField>
    <fullName>Investment_Likely_Amount_USD_mn__c</fullName>
    <label>Investment Likely Amount (mn)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Potential_Management_Fee__c.field-meta.xml
<CustomField>
    <fullName>Potential_Management_Fee__c</fullName>
    <label>Potential Management Fee%</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Reason_for_Decline__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Decline__c</fullName>
    <label>Reason for Decline</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lack of Capital</fullName>
            </value>
            <value>
                <fullName>No Reason Given</fullName>
            </value>
            <value>
                <fullName>Not ready-6 months</fullName>
            </value>
            <value>
                <fullName>Portfolio Performance</fullName>
            </value>
            <value>
                <fullName>Uninterested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Sent PPM</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Initial Meeting</fullName>
            </value>
            <value>
                <fullName>Second Meeting</fullName>
            </value>
            <value>
                <fullName>Follow up Diligence</fullName>
            </value>
            <value>
                <fullName>Soft Circle</fullName>
            </value>
            <value>
                <fullName>Verbal Commitment</fullName>
            </value>
            <value>
                <fullName>Legal Closed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/Navatar_Setup__c.object-meta.xml
<CustomObject>
    <label>Navatar Setup</label>
    <nameField>
        <displayFormat>NS - {0000000000}</displayFormat>
        <label>Navatar Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/fields/Admin_Setting__c.field-meta.xml
<CustomField>
    <fullName>Admin_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Setting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CCS__c.field-meta.xml
<CustomField>
    <fullName>CCS__c</fullName>
    <label>CCS</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CCS_Fundraising__c.field-meta.xml
<CustomField>
    <fullName>CCS_Fundraising__c</fullName>
    <label>CCS Fundraising</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CCS_New_Limited_Partner__c.field-meta.xml
<CustomField>
    <fullName>CCS_New_Limited_Partner__c</fullName>
    <label>CCS New Limited Partner</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CCS_Partnership__c.field-meta.xml
<CustomField>
    <fullName>CCS_Partnership__c</fullName>
    <label>CCS Partnership</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Org_Setting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/Partnership__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/fields/Fund_Investment_Category__c.field-meta.xml
<CustomField>
    <fullName>Fund_Investment_Category__c</fullName>
    <label>Fund Investment Category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/fields/Total_Commitments__c.field-meta.xml
<CustomField>
    <fullName>Total_Commitments__c</fullName>
    <description>this will be a formula field</description>
    <label>Total Commitments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/Test_CommitmentCreationSetup_Ctlr.cls
@isTest
public class Test_CommitmentCreationSetup_Ctlr{
    public static testMethod void Test_CommitmentCreationSetup() {   
        //  try {
            
        string nsp = CommonUtility.strNameSpacePrefix; 
        nsp = nsp.toLowerCase();
        System.assertNotEquals('testingHello', nsp); // (PE3.5, SK, 9Aug2017)
        
        // Null Web Service mock implementation
        System.Test.setMock(WebServiceMock.class, new MetadataServiceTest.WebServiceMockImpl());
        
        // Only required to workaround a current code coverage bug in the platform
        MetadataService metaDataService = new MetadataService();
        
        // Invoke operations         
        MetadataService.MetadataPort metaDataPort = new MetadataService.MetadataPort();
        // metaDataPort.listMetadata(null, null);
        // metaDataPort.updateMetadata(null);
        
        List<Org_Setting__mdt> lstOrgSett =[SELECT IsActive__c,label,developername FROM Org_Setting__mdt where developername ='Commitment_Creation' limit 1];
        
        Navatar_Setup__c navSetup= new Navatar_Setup__c();
        
        navSetup.ccs__c = ''+nsp+'commitment__c:'+nsp+'partner_type__c,'+nsp+'commitment__c:'+nsp+'tax_forms__c,'+nsp+'commitment__c:'+nsp+'allowchange__c;'+nsp+'commitment__c:'+nsp+'kyc__c,'+nsp+'commitment__c:'+nsp+'checkmultipiclist__c,'+nsp+'commitment__c:'+nsp+'has_child__c';
        navSetup.ccs_fundraising__c = ''+nsp+'fundraising__c:name,'+nsp+'fundraising__c:'+nsp+'legal_name__c,'+nsp+'fundraising__c:'+nsp+'investment_likely_amount_usd_mn__c,'+nsp+'fundraising__c:'+nsp+'target_close_date_del__c,'+nsp+'fundraising__c:'+nsp+'reason_for_decline__c;'+nsp+'fundraising__c:'+nsp+'fund_name__c,'+nsp+'fundraising__c:'+nsp+'portfolio_company__c,'+nsp+'fundraising__c:'+nsp+'potential_management_fee__c,'+nsp+'fundraising__c:'+nsp+'stage__c,'+nsp+'fundraising__c:'+nsp+'next_step__c';
        navSetup.ccs_new_limited_partner__c = 'LimitedPartner;account:name,account:'+nsp+'testdoublefield__c,account:'+nsp+'geographic_region__c,account:'+nsp+'closing_data_date__c';
        navSetup.ccs_partnership__c = ''+nsp+'partnership__c:'+nsp+'fund__c,'+nsp+'partnership__c:name,'+nsp+'partnership__c:'+nsp+'fund_investment_category__c,'+nsp+'partnership__c:'+nsp+'total_commitments__c';
        navSetup.admin_setting__c    =  true;
        insert navSetup;
        System.assertEquals(true, navSetup.admin_setting__c); // (PE3.5, SK, 9Aug2017)
        
        CommitmentCreationSetup_Ctlr cmtSetup= new  CommitmentCreationSetup_Ctlr();
        cmtSetup.describeSObjectSample();
        cmtSetup.onEditCommitmentSetup();
        cmtSetup.onSaveCommitmentSetup();
        cmtSetup.displayRecordTypeName();
        cmtSetup.resetDefaultValue();
        cmtSetup.onCancel();
        cmtSetup.strNameSpace = nsp;
        
        if(lstOrgSett[0].IsActive__c==true){
            cmtSetup.strEnableCMTSetup = false;
        }
        else{
             cmtSetup.strEnableCMTSetup = true;
        }
        cmtSetup.updateMetadataMethod(true);
        
        // Reference types
        new MetadataService();
        new MetadataService.listMetadataResponse_element();       
        new MetadataService.LogInfo();
        new MetadataService.Layout();        
        new MetadataService.CallOptions_element();
        new MetadataService.LayoutColumn();
        new MetadataService.FileProperties();      
        new MetadataService.ListMetadataQuery();
        new MetadataService.DebuggingHeader_element();
        new MetadataService.CustomConsoleComponents();
        new MetadataService.SubtabComponents();
        new MetadataService.SummaryLayoutItem();
        new MetadataService.LayoutSection();
        new MetadataService.listMetadata_element();
        new MetadataService.Metadata();
        new MetadataService.LayoutItem();
        new MetadataService.SaveResult();
        
        // CommitmentCreationSetup_Ctlr cmtSetup2= new  CommitmentCreationSetup_Ctlr();
        //} catch (Exception e) {
        //      System.assert(false, 'Exception ' + e);
        // }
    }
}