unpackaged/main/default/objects/Account/fields/Familiar_Name__c.field-meta.xml
<CustomField>
    <fullName>Familiar_Name__c</fullName>
    <description>Nick name for Institution</description>
    <label>Familiar Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Watchlist</fullName>
            </value>
            <value>
                <fullName>Under Evaluation</fullName>
                <default>true</default>
                <label>Under Evaluation</label>
            </value>
            <value>
                <fullName>Portfolio Company</fullName>
            </value>
            <value>
                <fullName>Sold/Exited</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Investment_Category__c.field-meta.xml
<CustomField>
    <fullName>Investment_Category__c</fullName>
    <label>Investment Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fund_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Co-investment</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/Fundraising__c.object-meta.xml
<CustomObject>
    <label>Fundraising</label>
    <nameField>
        <label>Fundraising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraisings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/Fundraising_Contact__c.object-meta.xml
<CustomObject>
    <label>Fundraising Contact</label>
    <nameField>
        <displayFormat>FC - {0}</displayFormat>
        <label>Fundraising Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProductSetting__c/ProductSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to manage trigger&#39;s(on Account and Fundraising) on/off functionality.</description>
    <label>PE Product Setting</label>
</CustomObject>

unpackaged/main/default/classes/Test_Fundraising.cls
@isTest
public class Test_Fundraising
{
    static string RecTypeInst='';
    static string RecTypeLP='';
    static  string RecTypeCompany='';
    static string RecTypeFM='';
    static string RecTypeFMF='';
    static  String RecTypeOther='';
    static     RecordType[] Rec;
    
    public static testmethod void ForFundraising()
    {
        Rec= [Select id,Name,SObjectType from RecordType where SObjectType='Account'];
        
        for(RecordType R:Rec)
        {
            // Institution replaced with Individual Investor by Sudhanshu on 06-11-2024
            if(R.Name == 'Individual Investor')
            {
                RecTypeInst= R.Id;
            }
            if(R.Name == 'Limited Partner')
            {
                RecTypeLP= R.Id;
            }
            if(R.Name == 'Company')
            {
                RecTypeCompany= R.Id;
            }
            if(R.Name == 'Fund Manager')
            {
                RecTypeFM= R.Id;
            }
            if(R.Name == 'Fund Manager’s Fund')
            {
                RecTypeFMF= R.Id;
            }
        }
        
          // Institution Scenario
        Account ins1=new Account(Name='ins1',RecordTypeId=RecTypeInst,Familiar_Name__c='ins1');  // Parent Institution is blank
        insert ins1;
        System.assertEquals('ins1', ins1.Name); // (PE3.5, SK, 8Aug2017)
        
        Account lp1=new Account( parentId=ins1.id,Name='lp1',RecordTypeId=RecTypeLP);
        insert lp1;
        System.assertEquals('lp1', lp1.Name); // (PE3.5, SK, 8Aug2017)
        
        Account Company1=new Account(Name='company',RecordTypeId=RecTypeCompany);
        insert Company1;
        System.assertEquals('company', Company1.Name); // (PE3.5, SK, 8Aug2017)
        
        Account fm1=new Account(Name='fund manager1',RecordTypeId=RecTypeFM);
        insert fm1;
        System.assertEquals('fund manager1', fm1.Name); // (PE3.5, SK, 8Aug2017)
        
        Account fmf1=new Account( parentId=fm1.id ,Name='fund managersfund1',RecordTypeId=RecTypeFMF);
        insert fmf1;
        System.assertEquals('fund managersfund1', fmf1.Name); // (PE3.5, SK, 8Aug2017)
        
        Contact contact1 = new Contact(lastname = 'Tester', AccountID=ins1.id);
        insert contact1;
        System.assertEquals('Tester', contact1.LastName); // (PE3.5, SK, 8Aug2017)

        Fund__c fund1 = new Fund__c(Name = '@isTest',Investment_Category__c = 'Fund');
        insert fund1;
        System.assertEquals('@isTest', fund1.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund__c coinv = new Fund__c(Name = '@isTest',Investment_Category__c = 'Co-Investment');
        insert coinv;
        System.assertEquals('@isTest', coinv.Name); // (PE3.5, SK, 8Aug2017)
        
        Fundraising__c fundr1= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=ins1.id,Portfolio_Company__c=company1.id);
        insert fundr1;
        System.assertEquals('TestFundraising', fundr1.Name); // (PE3.5, SK, 8Aug2017)
        
        Fundraising_Contact__c fundrsingcontact=new Fundraising_Contact__c(Fundraising__c=fundr1.Id,Contact__c=contact1.Id);
        insert fundrsingcontact;
        System.assertNotEquals('', fundrsingcontact.Name); // (PE3.5, SK, 8Aug2017)
        
        ProductSetting__c.getInstance('FundraisingwithFM').status__c=false;
        update ProductSetting__c.getInstance('FundraisingwithFM');
        
        ProductSetting__c.getInstance('FundraisingwithFMF').status__c=false;
        update ProductSetting__c.getInstance('FundraisingwithFMF');
        
        Fundraising__c fundr2= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=Company1.id,Portfolio_Company__c=company1.id);
        try
        {
            insert fundr2;
            System.assertEquals('TestFundraising', fundr2.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        
        Fundraising__c fundr3= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=fm1.id,Portfolio_Company__c=company1.id);
        try
        {
            insert fundr3;
            System.assertEquals('TestFundraising', fundr3.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        Fundraising__c fundr41= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=ins1.id,Portfolio_Company__c=ins1.id);
        try
        {
            insert fundr41;
            System.assertEquals('TestFundraising', fundr41.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
         Fundraising__c fundr4_11= new Fundraising__c(Name='TestFundraising',Fund_Name__c=fund1.id, Legal_Name__c=ins1.id,Portfolio_Company__c=company1.id);
        try
        {
            insert fundr4_11;
            System.assertEquals('TestFundraising', fundr4_11.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        Fundraising__c fundr4_1= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=ins1.id,Portfolio_Company__c=null);
        try
        {
            insert fundr4_1;
            System.assertEquals('TestFundraising', fundr4_1.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        Fundraising__c fundr4= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=fmf1.id,Portfolio_Company__c=company1.id);
        try
        {
            insert fundr4;
            System.assertEquals('TestFundraising', fundr4.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        Fundraising__c fundr5= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id);
        try
        {
            insert fundr5;
            System.assertEquals('TestFundraising', fundr5.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        fundr1.Legal_Name__c=fmf1.id;
        try
        {
            update fundr1;
        }
        catch(Exception e)
        {
        
        }
        Fundraising__c fundr6= new Fundraising__c(Name='TestFundraising', Legal_Name__c=fmf1.id,Portfolio_Company__c=company1.id);
        try
        {
            insert fundr6;
            System.assertEquals('TestFundraising', fundr6.Name); // (PE3.5, SK, 8Aug2017)
        }
        catch(Exception e)
        {
        
        }
        
    }
}