unpackaged/main/default/objects/Account/fields/Familiar_Name__c.field-meta.xml
<CustomField>
    <fullName>Familiar_Name__c</fullName>
    <description>Nick name for Institution</description>
    <label>Familiar Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/HasPipeline__c.field-meta.xml
<CustomField>
    <fullName>HasPipeline__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created to be deleted later</description>
    <label>HasPipeline</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <label>Advisor</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Advisor__c/Advisor__c.object-meta.xml
<CustomObject>
    <label>Advisor</label>
    <nameField>
        <displayFormat>A - {0}</displayFormat>
        <label>Advisor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advisor__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advisor__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advisor__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advisor__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Accountant - Tax</fullName>
            </value>
            <value>
                <fullName>Accountant - Financial</fullName>
            </value>
            <value>
                <fullName>Management Affiliate/Executive Board</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Bank Debt</fullName>
            </value>
            <value>
                <fullName>Bank M&amp;A</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Sell-side Advisor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Investment_Category__c.field-meta.xml
<CustomField>
    <fullName>Investment_Category__c</fullName>
    <label>Investment Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fund_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Co-investment</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/Fundraising__c.object-meta.xml
<CustomObject>
    <label>Fundraising</label>
    <nameField>
        <label>Fundraising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraisings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Test_Advisor.cls
@isTest
public class Test_Advisor
{
    static string RecTypeInst='';
    static string RecTypeLP='';
    static  string RecTypeCompany='';
    static string RecTypeFM='';
    static string RecTypeFMF='';
   // static  String RecTypeOther='';
    static  RecordType[] Rec;
    public static testmethod void ForAdvisor()
    {
        Rec= [Select id,Name,SObjectType from RecordType where SObjectType='Account'];
        
        for(RecordType R:Rec)
        {
            // Institution replaced with Individual Investor by Sudhanshu on 06-11-2024
            if(R.Name == 'Individual Investor')
            {
                RecTypeInst= R.Id;
            }
            if(R.Name == 'Limited Partner')
            {
                RecTypeLP= R.Id;
            }
            if(R.Name == 'Company')
            {
                RecTypeCompany= R.Id;
            }
            if(R.Name == 'Fund Manager')
            {
                RecTypeFM= R.Id;
            }
            if(R.Name == 'Fund Manager’s Fund')
            {
                RecTypeFMF= R.Id;
            }
            if(R.Name == 'Test')
            {
              //  RecTypeOther= R.Id;
            }
        }
        
        Account inst = new Account(RecordTypeId = RecTypeInst,Familiar_Name__c='@isTest1',Name='@isTest1');
        insert inst;
        Account inst2 = new Account(RecordTypeId = RecTypeInst,Familiar_Name__c='@isTest2',Name='@isTest2');
        insert inst2;
        Account limpart = new Account(RecordTypeId = RecTypeLP,Name='@isTest',ParentId = inst.Id);
        insert limpart;
        Account com = new Account(RecordTypeId = RecTypeCompany,Name='@isTest', HasPipeline__c = false);
        insert com;
               
        Account fm1=new Account(Name='fund manager1',RecordTypeId=RecTypeFM);
        insert fm1;
        Account fmf1=new Account( parentId=fm1.id ,Name='fund managersfund1',RecordTypeId=RecTypeFMF);
        insert fmf1;
        
      //  Account test1 = new Account(RecordTypeId = RecTypeOther,Name='@isTest');
       // insert test1;
               
        Fund__c fund = new Fund__c(Name = '@isTest',Investment_Category__c = 'Fund');
        insert fund;
        
        Fund__c coinv = new Fund__c(Name = '@isTest',Investment_Category__c = 'Co-Investment');
        insert coinv;
        
        Fundraising__c fd1 = new Fundraising__c(Name = '@isTest',Fund_Name__c = fund.Id,Legal_Name__c = inst.Id);      
        insert fd1;
        System.assert(fd1.Id!=null);
        Fundraising__c fd2 = new Fundraising__c(Name = '@isTest',Fund_Name__c = coinv.Id,Legal_Name__c = limpart.Id);
        try
        {
            insert fd2;
        }
         catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        Fundraising__c fd3 = new Fundraising__c(Name = '@isTest',Fund_Name__c = fund.Id,Legal_Name__c = fm1.Id);
        try
        {
            insert fd3;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
               
        Advisor__c ad1 = new Advisor__c(Advisor__c = inst.Id ,client__c =inst2.Id,Role__c = 'Advisor');
        insert ad1;
        
        ad1.Role__c='Legal';
        try
        {
            update ad1;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        
        Advisor__c ad10 = new Advisor__c(Advisor__c = inst.Id ,client__c =inst2.Id,Role__c = 'Advisor');
       try
        {
            insert ad10;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        
         Advisor__c ad11 = new Advisor__c(Advisor__c = inst.Id ,client__c =inst2.Id,Role__c = 'Advisor',Fundraising__c = fd1.Id);
        insert ad11;
        
        ad11.advisor__c = inst2.Id;
        try
        {
            update ad11;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        
        Advisor__c ad6 = new Advisor__c(Advisor__c = inst.Id ,client__c =inst2.Id,Role__c = 'Advisor',Fundraising__c = fd2.Id);
        try
        {
            insert ad6;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        
       // Advisor__c ad8 = new Advisor__c(Advisor__c = inst.Id ,client__c =test1.Id,Role__c = 'Advisor',Fundraising__c = fd2.Id);
        try
        {
          //  insert ad8;
        }
        catch(Exception e)
        {
          //  System.assert(ApexPages.hasMessages()==True);
        }
        
//Advisor__c ad9 = new Advisor__c(Advisor__c = test1.Id ,client__c =inst.Id,Role__c = 'Advisor',Fundraising__c = fd2.Id);
        try
        {
         //   insert ad9;
        }
        catch(Exception e)
        {
          //  System.assert(ApexPages.hasMessages()==True);
        }
               
        Advisor__c ad5 = new Advisor__c(Advisor__c = inst.Id ,client__c =inst2.Id,Role__c = 'Advisor' );
        try
        {
            insert ad5;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        Advisor__c ad2 = new Advisor__c(Advisor__c = inst.Id ,client__c =inst.Id,Role__c = 'Advisor');
        try
        {
            insert ad2;
        }
         catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        Advisor__c ad3 = new Advisor__c(Advisor__c = inst.Id ,client__c =limpart.Id,Role__c = 'Advisor' );
        try
        {
            insert ad3;
        }
        catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        Advisor__c ad4 = new Advisor__c(Advisor__c = com.Id ,client__c =inst.Id,Role__c = 'Advisor' );
        try
        {
            insert ad4;
        }
         catch(Exception e)
        {
            System.assert(ApexPages.hasMessages()==True);
        }
        ad11.advisor__c = inst2.Id;
        ad11.Client__c = inst.Id;
        ad11.Fundraising__c = fd1.Id;
        try
        {
            update ad1;
        }
         catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        
        ad4.advisor__c = inst2.Id;
        try
        {
            update ad4;
        }
         catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        
        ad3.Client__c = com.Id;
        try
        {
            update ad3;
        }
         catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        
        ad3.Fundraising__c = fd1.Id;
        try
        {
            update ad3;
        }
         catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
    }
}