unpackaged/main/default/objects/Account/fields/Familiar_Name__c.field-meta.xml
<CustomField>
    <fullName>Familiar_Name__c</fullName>
    <description>Nick name for Institution</description>
    <label>Familiar Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Quarterly_Financial_Performance__c/Quarterly_Financial_Performance__c.object-meta.xml
<CustomObject>
    <label>Quarterly Financial Performance</label>
    <nameField>
        <displayFormat>QFP-{0}</displayFormat>
        <label>Quarterly Financial Performance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quarterly Financial Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quarterly_Financial_Performance__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quarterly Financial Performances</relationshipLabel>
    <relationshipName>Quarterly_Financial_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Quarterly_Financial_Performance__c/fields/Fiscal_Year_end__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_end__c</fullName>
    <label>Fiscal Year end</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quarterly_Financial_Performance__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quarterly_Financial_Performance__c/fields/Quarter_end_Date__c.field-meta.xml
<CustomField>
    <fullName>Quarter_end_Date__c</fullName>
    <label>Quarter-end Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/Test_Quarterly_Financial_Performance.cls
@isTest
public class Test_Quarterly_Financial_Performance
{
    static string RecTypeInst='';
    static string RecTypeLP='';
    static  string RecTypeCompany='';
    static string RecTypeFM='';
    static string RecTypeFMF='';
   // static  String RecTypeOther='';
    static  RecordType[] Rec;
    public static testmethod void ForQuarterlyFinancialPerformance()
    {
        Rec= [Select id,Name,SObjectType from RecordType where SObjectType='Account'];
        
        for(RecordType R:Rec)
        {
            if(R.Name == 'Institution')
            {
            RecTypeInst= R.Id;
            }
            if(R.Name == 'Limited Partner')
            {
            RecTypeLP= R.Id;
            }
            if(R.Name == 'Company')
            {
            RecTypeCompany= R.Id;
            }
            if(R.Name == 'Fund Manager')
            {
            RecTypeFM= R.Id;
            }
            if(R.Name == 'Fund Manager’s Fund')
            {
            RecTypeFMF= R.Id;
            }
            if(R.Name == 'Test')
            {
            //  RecTypeOther= R.Id;
            }
        }
             
         Account inst = new Account(RecordTypeId = RecTypeInst,Familiar_Name__c='@isTest1',Name='@isTest1');
        insert inst;
        Account limpart = new Account(RecordTypeId = RecTypeLP,Name='@isTest',ParentId = inst.Id);
        insert limpart;
        Account com = new Account(RecordTypeId = RecTypeCompany,Name='@isTest');
        insert com;
        Account fm1=new Account(Name='fund manager1',RecordTypeId=RecTypeFM);
        insert fm1;
        Account fmf1=new Account( parentId=fm1.id ,Name='fund managersfund1',RecordTypeId=RecTypeFMF);
        insert fmf1;
      //   Account test1 = new Account(RecordTypeId = RecTypeOther,Name='@isTest');
      //  insert test1;
        
        Quarterly_Financial_performance__c qfp1 = new Quarterly_Financial_performance__c(Company__c = inst.Id,Quarter_end_Date__c = System.today(), Fiscal_Year_end__c = System.today(),Quarter__c = 'Q1');
         insert qfp1;
         System.assert(qfp1.Id!=null);
        Quarterly_Financial_performance__c qfp2 = new Quarterly_Financial_performance__c(Company__c = limpart.Id,Quarter_end_Date__c  = System.today(),Fiscal_Year_end__c = System.today(),Quarter__c = 'Q1');
        insert qfp2;
       System.assert(qfp2.Id!=null);
        Quarterly_Financial_performance__c qfp3 = new Quarterly_Financial_performance__c(Company__c = com.Id,Quarter_end_Date__c  = System.today(),Fiscal_Year_end__c = System.today(),Quarter__c = 'Q1');
        insert qfp3;
        System.assert(qfp3.Id != null);
        
         Quarterly_Financial_performance__c qfp4 = new Quarterly_Financial_performance__c(Company__c = fm1.Id,Quarter_end_Date__c  = System.today(),Fiscal_Year_end__c = System.today(),Quarter__c = 'Q1');
        try
        {
            insert qfp4;
        }
        catch(Exception e)
        {
            System.assert(qfp4.Id==null);
        }
        Quarterly_Financial_performance__c qfp5 = new Quarterly_Financial_performance__c(Company__c = fmf1.Id,Quarter_end_Date__c  = System.today(),Fiscal_Year_end__c = System.today(),Quarter__c = 'Q1');
        try
        {
            insert qfp5;
        }
        catch(Exception e)
        {
            System.assert(qfp5.Id==null);
        }
      //  Quarterly_Financial_performance__c qfp6 = new Quarterly_Financial_performance__c(Company__c = test1.Id,Quarter_end_Date__c  = System.today(),Fiscal_Year_end__c = System.today(),Quarter__c = 'Q1');
        try
        {
         //   insert qfp6;
        }
        catch(Exception e)
        {
          //  System.assert(qfp6.Id==null);
        }
}
}