unpackaged/main/default/objects/Account/fields/Familiar_Name__c.field-meta.xml
<CustomField>
    <fullName>Familiar_Name__c</fullName>
    <description>Nick name for Institution</description>
    <label>Familiar Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Watchlist</fullName>
            </value>
            <value>
                <fullName>Under Evaluation</fullName>
                <default>true</default>
                <label>Under Evaluation</label>
            </value>
            <value>
                <fullName>Portfolio Company</fullName>
            </value>
            <value>
                <fullName>Sold/Exited</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Advisor__c/Advisor__c.object-meta.xml
<CustomObject>
    <label>Advisor</label>
    <nameField>
        <displayFormat>A - {0}</displayFormat>
        <label>Advisor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advisor__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advisor__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advisor__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Advisors</relationshipLabel>
    <relationshipName>Advisor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/Commitment__c.object-meta.xml
<CustomObject>
    <label>Commitment</label>
    <nameField>
        <displayFormat>CMT - {000000}</displayFormat>
        <label>Commitment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commitment__c/fields/Commitment_Amount_nearest__c.field-meta.xml
<CustomField>
    <fullName>Commitment_Amount_nearest__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commitment Amount</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Limited_Partner__c.field-meta.xml
<CustomField>
    <fullName>Limited_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limited Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <referenceTo>Partnership__c</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Investment_Category__c.field-meta.xml
<CustomField>
    <fullName>Investment_Category__c</fullName>
    <label>Investment Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fund_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Co-investment</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/Fundraising__c.object-meta.xml
<CustomObject>
    <label>Fundraising</label>
    <nameField>
        <label>Fundraising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraisings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/Fundraising_Contact__c.object-meta.xml
<CustomObject>
    <label>Fundraising Contact</label>
    <nameField>
        <displayFormat>FC - {0}</displayFormat>
        <label>Fundraising Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/Partnership__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProductSetting__c/ProductSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to manage trigger&#39;s(on Account and Fundraising) on/off functionality.</description>
    <label>PE Product Setting</label>
</CustomObject>

unpackaged/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transfer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transfer__c/fields/Commitment_Name__c.field-meta.xml
<CustomField>
    <fullName>Commitment_Name__c</fullName>
    <label>Commitment Name</label>
    <referenceTo>Commitment__c</referenceTo>
    <relationshipLabel>Transferred Amount from Commitment</relationshipLabel>
    <relationshipName>Transfer_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Transfer__c/fields/Transfer_Amount_nearest__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Amount_nearest__c</fullName>
    <label>Transfer Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Transfer__c/fields/Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Transfer Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Transfer__c/fields/Transfer_to_Limited_Partner__c.field-meta.xml
<CustomField>
    <fullName>Transfer_to_Limited_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer to Limited Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transfers</relationshipLabel>
    <relationshipName>Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transfer__c/fields/Transfer_to_Partnership__c.field-meta.xml
<CustomField>
    <fullName>Transfer_to_Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer to Partnership</label>
    <referenceTo>Partnership__c</referenceTo>
    <relationshipLabel>Transfers made to Partnership</relationshipLabel>
    <relationshipName>Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Test_AccountTrigger2.cls
@isTest(seeAllData =false)
public class Test_AccountTrigger2
{
    static string RecTypeInst='';
    static string RecTypeLP='';
    static  string RecTypeCompany='';
    static string RecTypeFM='';
    static string RecTypeFMF='';
    static  String RecTypeOther='';
    static     RecordType[] Rec;
    
    
    public void testDataSetUP(){
        String tempStr = 'testing...';
        System.assertEquals('testing...', tempStr); // (PE3.5, SK, 9Aug2017)
    }
    
    
    public static testmethod void Fordeletion()
    {
        Test.startTest();
        Rec= [Select id,Name,SObjectType from RecordType where SObjectType='Account'];
        
        for(RecordType R:Rec)
        {
            if(R.Name == 'Institution')
            {
                RecTypeInst= R.Id;
            }
            else if(R.Name == 'Limited Partner')
            {
                RecTypeLP= R.Id;
            }
            else if(R.Name == 'Company')
            {
                RecTypeCompany= R.Id;
            }
            else if(R.Name == 'Fund Manager')
            {
                RecTypeFM= R.Id;
            }
            else if(R.Name == 'Fund Manager’s Fund')
            {
                RecTypeFMF= R.Id;
            }
            else
            {
            RecTypeOther= R.Id;
            }
        }
        
        Account ins1=new Account(Name='ins1',RecordTypeId=RecTypeInst,Familiar_Name__c='ins1');  // Parent Institution is blank
        insert ins1;
        
        Account ins2=new Account(Name='ins1',RecordTypeId=RecTypeInst,Familiar_Name__c='ins1');  // Parent Institution is blank
        insert ins2;
        
        Account ins3=new Account(Name='ins1',RecordTypeId=RecTypeInst,Familiar_Name__c='ins1');  // Parent Institution is blank
        insert ins3;
        
        Account lp1=new Account( parentId=ins1.id,Name='lp1',RecordTypeId=RecTypeLP);
        insert lp1;
            
        Account fundmanager=new Account( Name='fundmanager',RecordTypeId=RecTypeFM);
        insert fundmanager;
            
        Account company2=new Account( Name='company2',RecordTypeId=RecTypeCompany);
        insert company2;
        
        Contact contact1 = new Contact(lastname = 'Tester', AccountID=ins1.id);
        insert contact1;
           
        Contact contact2 = new Contact(lastname = 'Tester', AccountID=fundmanager.id);
        insert contact2;
        
        Contact contact3 = new Contact(lastname = 'Tester', AccountID=company2.id);
        insert contact3;
        
        Contact contact4 = new Contact(lastname = 'Tester', AccountID=lp1.id);
        insert contact4;
          
           
            
        Account Company1=new Account(Name='company',RecordTypeId=RecTypeCompany);
        insert Company1;
            
        Fund__c coinv = new Fund__c(Name = '@isTest',Investment_Category__c = 'Co-Investment');
        insert coinv;
             
        Partnership__c part1 = new Partnership__c(Name='Part',Fund__c=coinv.Id);
        insert part1;
            
        Partnership__c part2 = new Partnership__c(Name='Part',Fund__c=coinv.Id);
        insert part2;
            
        Commitment__c commitment1=new Commitment__c(Limited_Partner__c=lp1.id,Partnership__c=part1.id, Portfolio_Company__c=Company1.Id,Commitment_Amount_nearest__c = 20000000);
        insert commitment1;
            
        Transfer__c transfer1= new Transfer__c(Commitment_Name__c=commitment1.Id, Transfer_Amount_nearest__c=10000000, Transfer_to_Limited_Partner__c=lp1.Id, Transfer_to_Partnership__c=part2.Id, Transfer_Date__c=System.Today());
        insert transfer1;
        
   /*     Fundraising__c fundr= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c=ins1.id,Portfolio_Company__c=company1.id);
        insert fundr;
             
        Fundraising_Contact__c fundrsingcontact=new Fundraising_Contact__c(Fundraising__c=fundr.Id,Contact__c=contact1.Id);
        insert fundrsingcontact;
            
        Fundraising_Contact__c fundrsingcontact1=new Fundraising_Contact__c(Fundraising__c=fundr.Id,Contact__c=contact2.Id);
        insert fundrsingcontact1;
             
        Fundraising_Contact__c fundrsingcontact2=new Fundraising_Contact__c(Fundraising__c=fundr.Id,Contact__c=contact3.Id);
        insert fundrsingcontact2;
            
        Fundraising_Contact__c fundrsingcontact3=new Fundraising_Contact__c(Fundraising__c=fundr.Id,Contact__c=contact4.Id);
        insert fundrsingcontact3;
            
        Advisor__c advisor1=new Advisor__c( Advisor__c=ins1.id,Client__c=ins2.id,Fundraising__c=fundr.id);
        insert advisor1;
        
        Advisor__c client1=new Advisor__c( Advisor__c=ins2.id,Client__c=ins1.id,Fundraising__c=fundr.id);
        //insert client1;
        lp1.parentId=company1.id;
            */
            
        cls_ProductSetting clsobj1=new cls_ProductSetting ();
        
        clsobj1.ObjFundraising_FM=new ProductSetting__c(name='FundraisingwithFM',status__c=true);
        insert clsobj1.ObjFundraising_FM;
        
        clsobj1.ObjFundraising_FMF=new ProductSetting__c(name='FundraisingwithFMF',status__c=true);
        insert clsobj1.ObjFundraising_FMF;
        
        ProductSetting__c ObjFundraising_FM;
        ProductSetting__c ObjFundraising_FMF;
        
        ObjFundraising_FM = ProductSetting__c.getInstance('FundraisingwithFM');
        ObjFundraising_FMF = ProductSetting__c.getInstance('FundraisingwithFMF');
        ObjFundraising_FM.status__c=false;
        ObjFundraising_FMF.status__c=false;
          
        update ObjFundraising_FM;
        update ObjFundraising_FMF;
        //Test.startTest();   
        account insfordelete=new account(name='fm',RecordTypeId=RecTypeInst);
        insert insfordelete;
           
        account insfordelete1=new account(name='fm',RecordTypeId=RecTypeInst);
        insert insfordelete1;
                  
        Account companyfordelete=new Account( Name='company2',RecordTypeId=RecTypeCompany);
        insert companyfordelete;
        
        Contact contactfordelete1 = new Contact(lastname = 'Tester', AccountID=insfordelete1.id);
        insert contactfordelete1;
        
        account fm1fordelete=new account(name='fm',RecordTypeId=RecTypeFM);
        insert fm1fordelete;
        
        Contact contactfordelete = new Contact(lastname = 'Tester', AccountID=fm1fordelete.id);
        insert contactfordelete;
        
        account fmf1fordelete=new account(name='fmf',parentId=fm1fordelete.id,RecordTypeId=RecTypeFMF);
        insert fmf1fordelete;
        
        
    //    Fundraising__c fundfordelete= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c= insfordelete.id,Portfolio_Company__c=company1.id);
    //    insert fundfordelete;
        
    //     Fundraising__c fundfordelete1= new Fundraising__c(Name='TestFundraising',Fund_Name__c=coinv.id, Legal_Name__c= insfordelete1.id,Portfolio_Company__c=company1.id);
    //    insert fundfordelete1;
        
    //    Fundraising_Contact__c fundrsingcontactfordelete=new Fundraising_Contact__c(Fundraising__c=fundfordelete.Id,Contact__c=contactfordelete.Id);
       // insert fundrsingcontactfordelete;
    //     Fundraising_Contact__c fundrsingcontactfordelete1=new Fundraising_Contact__c(Fundraising__c=fundfordelete1.Id,Contact__c=contactfordelete1.Id);
   //     insert fundrsingcontactfordelete1;
        
        Test.stopTest();
        
        try
        {
            update lp1;
        }
        catch(Exception e)
        {
         //  System.assert(ApexPages.hasMessages()==True);
        }
        try
        {
            // delete ins1;
        }
        catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        try
        {
           // delete lp1;
        }
        Catch(Exception e)
        {
           //  System.assert(ApexPages.hasMessages()==True);
        }
        try
        {
            //delete company1;
        }
        catch(Exception e)
        {
            // System.assert(ApexPages.hasMessages()==True);
        }
        try
        {
            //delete company2;
        }
        catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
         try
        {
            //delete fundmanager;
        }
        catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        try
        {
          //  delete fmf1fordelete;
        }
        catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        try
        {
            //delete fm1fordelete;
        }
        catch(Exception e)
        {
             System.assert(ApexPages.hasMessages()==True);
        }
        
        
    }
}