unpackaged/main/default/objects/Account/fields/Familiar_Name__c.field-meta.xml
<CustomField>
    <fullName>Familiar_Name__c</fullName>
    <description>Nick name for Institution</description>
    <label>Familiar Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/HasPipeline__c.field-meta.xml
<CustomField>
    <fullName>HasPipeline__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created to be deleted later</description>
    <label>HasPipeline</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Pipeline__c/Pipeline__c.object-meta.xml
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pipeline__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deal Received</fullName>
            </value>
            <value>
                <fullName>NDA Signed</fullName>
            </value>
            <value>
                <fullName>Management Meeting</fullName>
            </value>
            <value>
                <fullName>IOI</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Declined/Dead</fullName>
            </value>
            <value>
                <fullName>Parked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Test_Pipeline.cls
@isTest
public class Test_Pipeline
{
    static string RecTypeInst='';
    static string RecTypeLP='';
    static  string RecTypeCompany='';
    static string RecTypeFM='';
    static string RecTypeFMF='';
    static String sCompanyApi =  CommonUtility.chkmasterLookupInPiplineAPI();
  //  static  String RecTypeOther='';
    static  RecordType[] Rec;
    public static testmethod void ForPipeline()
    {
        Rec= [Select id,Name,SObjectType from RecordType where SObjectType='Account'];
        
        for(RecordType R:Rec)
        {
            if(R.Name == 'Institution')
            {
            RecTypeInst= R.Id;
            }
            if(R.Name == 'Limited Partner')
            {
            RecTypeLP= R.Id;
            }
            if(R.Name == 'Company')
            {
            RecTypeCompany= R.Id;
            }
            if(R.Name == 'Fund Manager')
            {
            RecTypeFM= R.Id;
            }
            if(R.Name == 'Fund Manager’s Fund')
            {
            RecTypeFMF= R.Id;
            }
            if(R.Name == 'Test')
            {
          //  RecTypeOther= R.Id;
            }
        }
        
        Account inst = new Account(RecordTypeId = RecTypeInst,Familiar_Name__c='@isTest1',Name='@isTest1');
        insert inst;
        Account limpart = new Account(RecordTypeId = RecTypeLP,Name='@isTest',ParentId = inst.Id);
        insert limpart;
        Account com = new Account(RecordTypeId = RecTypeCompany,Name='@isTest', HasPipeline__c = false);
        insert com;
        
        Account fm1=new Account(Name='fund manager1',RecordTypeId=RecTypeFM);
        insert fm1;
        Account fmf1=new Account( parentId=fm1.id ,Name='fund managersfund1',RecordTypeId=RecTypeFMF);
        insert fmf1;
        
      //  Account test1 = new Account(RecordTypeId = RecTypeOther,Name='@isTest');
      //  insert test1;
        
     //   Pipeline__c pipe6 = new Pipeline__c(Name = '@isTest',Company_Name__c =test1.Id,Stage__c = 'LOI');
        try
        {
        //   insert pipe6;
        }
         catch(Exception e)
        {
           // System.assert(pipe6.Id == null);
        }
        
        Pipeline__c pipe1 = new Pipeline__c(Name = '@isTest', Stage__c = 'LOI');
        pipe1.put(sCompanyApi, inst.Id);
        try
        {
           insert pipe1;
        }
         catch(Exception e)
        {
            System.assert(pipe1.Id == null);
        }
        
       Pipeline__c pipe3 = new Pipeline__c(Name = '@isTest', Stage__c = 'LOI');
        pipe3.put(sCompanyApi, com.Id);
       insert pipe3;
       
       System.assert(pipe3.Id != null);
       
        Pipeline__c pipe4 = new Pipeline__c(Name = '@isTest1', Stage__c = 'LOI',Log_In_Date__c=Date.valueOf('2012-3-4'));
        pipe4.put(sCompanyApi, com.Id);
       insert pipe4;
       
       System.assert(pipe4.Id != null);
       
       Pipeline__c pipe5 = new Pipeline__c(Name = '@isTest1', Stage__c = 'LOI',Log_In_Date__c=Date.valueOf('2012-2-2'));
        pipe5.put(sCompanyApi, com.Id);
       insert pipe5;
       
       System.assert(pipe5.Id != null);
       
       pipe4.Log_In_Date__c=Date.valueOf('2012-1-1');
       
          
        update pipe4;
        
        pipe4.Log_In_Date__c=Date.valueOf('2012-7-7');
        update pipe4;
        
        delete pipe4;
        delete pipe5;
        delete pipe3;
        
        
             
        
        
        
        
}
}