unpackaged/main/default/objects/Account/fields/Touchpoint_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Overdue__c</fullName>
    <formula>Today() &gt; Next_Touchpoint_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Touchpoint Overdue</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Touchpoint_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint_Overdue__c</fullName>
    <formula>Today() &gt;  Next_Touchpoint_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Touchpoint Overdue</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/NavatarExpBuilderLookupPopupCtrlTest.cls
/*
Class        : NavatarExpBuilderLookupPopupCtrlTest
Main Class   : NavatarExpBuilderLookupPopupCtrl
Created By   : Kushal
Created Date : 17-Feb-2023
*/
@isTest
public class NavatarExpBuilderLookupPopupCtrlTest {
	@isTest
    public static void method1() {
        NavatarExpBuilderLookupPopupCtrl.responseData res1 = NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Contact', 'AccountId', 'REFERENCE', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Contact', 'LeadSource', 'PICKLIST', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Contact', 'navpeII_dev18__Industry_Focus__c', 'PICKLIST', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Contact', 'Touchpoint_Overdue__c', 'PICKLIST', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Account', 'Source', 'Picklist', '');
        //NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Contact Role', 'Name', 'Picklist', '');
        //NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Target', 'Source', 'Picklist', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('FUND', 'Name', 'Text', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('FUNDRAISING', 'Name', 'Text', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('FUNDRAISING CONTACT', 'Name', 'Text', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('DEAL', 'Name', 'Text', '');
        NavatarExpBuilderLookupPopupCtrl.getLookUpValues('Marketing Prospect', 'Name', 'Text', '');
        
        NavatarExpBuilderLookupPopupCtrl.SearchItem('Test', 'Contact', '1');
        System.Assert(res1 != null, true);
    }
}