unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Location(Delete)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Office_Location__c.Organization_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Fund_Type__c.field-meta.xml
<CustomField>
    <fullName>Fund_Type__c</fullName>
    <label>Fund Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fund</fullName>
            </value>
            <value>
                <fullName>Fund of Funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/Fundraising__c.object-meta.xml
<CustomObject>
    <label>Fundraising</label>
    <nameField>
        <label>Fundraising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraisings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/Fundraising_Contact__c.object-meta.xml
<CustomObject>
    <label>Fundraising Contact</label>
    <nameField>
        <displayFormat>FC - {0}</displayFormat>
        <label>Fundraising Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <description>If you mark this as primary; it will automatically update Billing Address of associated account.</description>
    <label>Office Location (Don&#39;t Use)</label>
    <nameField>
        <displayFormat>OL - {0000000000}</displayFormat>
        <label>Office Location ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Office Locations (Don&#39;t Use)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Office_Location__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Office_Locations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Test_massemail_Fundraising.cls
/*  New Implimentation:
        Developer               :  Bvenkat Jeewesh
        Product Version         :   PE V3.0
        date of Creation        :   18/05/2015
        Purpose of Creation     :   Custom Controller For massemailFundraising Page
                                    Code Coverage for massemailFundraising Class
        */
@isTest(SeeAllData=true)
public class Test_massemail_Fundraising
{   
    static testMethod void testMethod1()
    {
            Account objacc=new Account();
            objacc.Name='test account';
            insert objacc;
            System.assertEquals('test account', objacc.Name); // (PE3.5, SK, 9Aug2017)
            
            Fund__c fundObj = new Fund__c(Name='testFund',Fund_Type__c='Fund');
            insert fundObj;  
            System.assertEquals('testFund', fundObj.Name); // (PE3.5, SK, 9Aug2017)   
            
            /*Office_Location__c objoff=new Office_Location__c();
            objoff.Name='test name';
            objoff.Organization_Name__c=objacc.id;
            objoff.City__c='test office city';
            objoff.State__c='test office staet';
            objoff.Country__c='test office country';
            objoff.Street__c='test office strewe';
            objoff.ZIP__c='test office staet';
            
            insert objoff;*/
            
            contact con = new contact();
            con.lastName = 'Test last Contact'; 
            con.firstname = 'Test First Name'; 
            con.HasOptedOutOfEmail=false;  
            con.MailingCity ='Test City'; 
            con.MailingCountry='Test country';  
            con.MailingPostalCode = '102010';
            con.MailingState = 'Test State';
            con.MailingStreet='Test street';
            con.Description='test hello how are you';
            con.Fax='012423';
            con.Phone = '01245263';
            con.otherCity = 'test other city';
            con.otherCountry='Test other country';  
            con.otherPostalCode = '1020101';
            con.otherState = 'Test other State';
            con.otherStreet='Test other street'; 
            con.accountid=objacc.id;
            //con.Office_Location__c=objoff.id;
            insert con;
            System.assertEquals('Test last Contact', con.LastName); // (PE3.5, SK, 9Aug2017)   
           
            Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Account; 
            Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
            
            Account acc = new Account(Name='test Account',recordtypeid=AccountRecordTypeInfo.get('Company').getRecordTypeId());
            insert acc;
            System.assertEquals('test Account', acc.Name); // (PE3.5, SK, 9Aug2017)   
            
           // Account Acc_comp1 = new Account(Name='test',recordtypeid=AccountRecordTypeInfo.get('Company').getRecordTypeId());
           // insert Acc_comp1;
        	// Institution replaced with Individual Investor by Sudhanshu on 06-11-2024
            Account Acc_inst = new Account(Name='test1',recordtypeid=AccountRecordTypeInfo.get('Individual Investor').getRecordTypeId());
            insert Acc_inst;
            System.assertEquals('test1', Acc_inst.Name); // (PE3.5, SK, 9Aug2017)   
           
            
            Fundraising__c objFR = new Fundraising__c(Name= 'Test Fundraising',Portfolio_Company__c=acc.id,Fund_Name__c=fundObj.id,Legal_Name__c=Acc_inst.id);      
            insert objFR;   
            System.assertEquals('Test Fundraising', objFR.Name); // (PE3.5, SK, 9Aug2017)
            
            Fundraising_Contact__c FC=new   Fundraising_Contact__c();
            FC.Contact__c=con.id;
            FC.Fundraising__c=objFR.id;   
            insert FC;
            System.assertNotEquals('Test last Contact', FC.Name); // (PE3.5, SK, 9Aug2017)   
            
            list<Fundraising__c> lstfr=new list<Fundraising__c>(); 
            lstfr.add(objFR);        
            
            Test.startTest();
            Apexpages.currentPage().getHeaders().put('USER-AGENT','MSIE');
            Apexpages.currentPage().getParameters().put('Fid',fundObj.id);
            Apexpages.currentPage().getParameters().put('Lid',Acc_inst.id);   
            //Apexpages.currentPage().getParameters().put('Fid',fundObj.id);
           // Apexpages.currentPage().getParameters().put('Lid','a0L36000004FOtd');           
        
            massemailFundraising objMEF = new massemailFundraising(new ApexPages.StandardSetController(lstfr));
        
        objMEF.cancel();
        objMEF.ETData();
        objMEF.getItems();
      
       // Apexpages.currentPage().getParameters().put('selectConIdFundrasingId','01p360000df8MIR@@01p360000df8MIR,01p360000df8MIR@@01p360000df8MIR');
        objMEF.selectConIdFundrasingId=con.id+'@@'+objFR.id+'@@'+FC.Id;
        integer Sendmailcount = 0;
        objMEF.bCC_Me_On_One= true;
        objMEF.use_My_Signature= true;
        objMEF.chkStoreActivity= true;
        objMEF.count=0;
        objMEF.sendmassmail();
        objMEF.bCC_Me_On_One= false;
        objMEF.sendmassmail();
        MassEmailFundraising.GetEmailLimit();
        Apexpages.currentPage().getParameters().put('Fid',null);
        Apexpages.currentPage().getParameters().put('Lid','a0L36000004FOtd');
        massemailFundraising objMEF1 = new massemailFundraising(new ApexPages.StandardSetController(lstfr));
        objMEF1.cancel();
        Test.stopTest();
    }
    
    
}