unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/SDG__c/fields/Enable_Inline_Edit__c.field-meta.xml
<CustomField>
    <fullName>Enable_Inline_Edit__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use this field to enable/disbale inline editing in the SDG.</description>
    <label>Enable Inline Edit</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/List_View_Name__c.field-meta.xml
<CustomField>
    <fullName>List_View_Name__c</fullName>
    <description>Use this field to specify the API Name of the Lightning List View. The SDG will then inherit the filter conditions applied for that List View.
Note: For an SDG, user can either fill &#39;Filter&#39; or &#39;List View Name&#39;.</description>
    <label>List View Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/My_Home__c.field-meta.xml
<CustomField>
    <fullName>My_Home__c</fullName>
    <defaultValue>false</defaultValue>
    <label>My Home</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/My_Teams_Records__c.field-meta.xml
<CustomField>
    <fullName>My_Teams_Records__c</fullName>
    <description>Use this field to specify the condition to display the records where logged-in user&#39;s team is associated with the record. E.g.: If there is a Contact’s SDG and the logged-in user wants to view the contacts where all his/her team members are the owners then write query as “(Owner.Id IN (SELECT Id FROM User WHERE Team__c = &#39;&lt;&lt;Team__c&gt;&gt;&#39;))”.
This will be further used by Universal Filter to display the desired filtered result.</description>
    <label>My Teams Records</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/MyRecords__c.field-meta.xml
<CustomField>
    <fullName>MyRecords__c</fullName>
    <description>Use this field to specify the condition to display the records where logged-in user is associated with the record. E.g.: If there is a Contact’s SDG and the logged in user wants to view the contacts where he/she is the Owner along with all the contacts where he/she is the Account Owner, then write query as “(Owner.ID = &lt;&lt;User.Id&gt;&gt; OR Account.OwnerId= &lt;&lt;User.Id&gt;&gt;)”.
This will be further used by Universal Filter to display the desired filtered result.</description>
    <label>My Records</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Show_Icon__c.field-meta.xml
<CustomField>
    <fullName>Show_Icon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Icon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/SDG_Field__c.object-meta.xml
<CustomObject>
    <label>Sortable Data Grid Field</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SDG_Field__c/fields/sdg__c.field-meta.xml
<CustomField>
    <fullName>sdg__c</fullName>
    <label>sdg</label>
    <referenceTo>SDG__c</referenceTo>
    <relationshipName>SDGFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/sdg_Preferences__c/sdg_Preferences__c.object-meta.xml
<CustomObject>
    <label>Sortable Data Grid Preference</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sortable Data Grid Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sdg_Preferences__c/fields/Filters__c.field-meta.xml
<CustomField>
    <fullName>Filters__c</fullName>
    <label>Filters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/sdg_Preferences__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sortable_Data_Grid_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/sdgControllerTest.cls
/*
* Copyright (c) 2018, salesforce.com, inc.
* All rights reserved.
* SPDX-License-Identifier: BSD-3-Clause
* For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
@isTest
public with sharing class sdgControllerTest {
    
    static testMethod void TestCustomObjInitialLoad()
    {
        //Generate test data: an account and an opportunity:
        String testdata=sdgTestData.GenerateTestSampleData();
        
        STring sdgid = sdgTestData.GenerateTestSDG();
        //do not generate any fields to get an error
        
        Test.startTest();
        
        String results = sdgController.GetSDGInitialLoad(testdata, testdata, 'Attachments', '',0);
        //json payload so parse
        SDGInitialLoad initial = (SDGInitialLoad)JSON.deserialize(results, SDGInitialLoad.class);
        system.assertEquals(true, initial.isError,'Expected error for SDG with no fields');
        
        Test.stopTest();
    }
    
    static testMethod void TestCustom()
    {
        SDG__c a = new SDG__c(Name='SDGName', sdg_tag__c = 'SDGName', is_valid__c=true, Myrecords__c='abc',sobjectname__c=sdgNamespaceUtility2.GetNamespace() + 'sdg_field__c', parent_field_name__c = sdgNamespaceUtility2.GetNamespace() + 'sdg__r.id');
        insert a;
        Test.startTest();
        //sdgController.deleteSdgPreference('abc:SDGName');
        sdgController.prepareDataForRow('select id from Account','SELECT Name, COUNT(Id) AccountCount FROM Account GROUP BY Name limit 10',a.id,true);
        sdgController.prepareDataForRow('select id from Account','SELECT Name, COUNT(Id) AccountCount FROM Account GROUP BY Name limit 10',a.id,false);
        // sdgController.getOwerIdFromSDGObj('abc:SDGName');
        sdgController.GetNamespace();
        sdgController.updateSdgPreference('SDGName',true);
        System.assertEquals('SDGName', a.Name); // added for security issues PEv4.7 by Aditya on 22 March 2021
        
        Test.stopTest();
    }
    
    static SDGResult GetResult(SDGRequest req)
    {
        String results = sdgController.getSDGResult(JSON.serialize(req));
        SDGResult result = (SDGResult)JSON.deserialize(results, SDGResult.class);
        return result;
        
    }
    
    static testMethod void TestInvalidSDG()
    {
        //Generate test data: an account and an opportunity:
        String testdatarecordid= sdgTestData.GenerateTestSampleData();
        
        STring erlid = sdgTestData.GenerateTestSDG();
        String stringfield = sdgTestData.GenerateTestSDGFieldString(erlid);
        String datefield = sdgTestData.GenerateTestSDGFieldDate(erlid);
        String booleanfield = sdgTestData.GenerateTestSDGFieldBoolean(erlid);
        String picklistfield = sdgTestData.GenerateTestSDGFieldPicklist(erlid);
        
        Test.startTest();
        
        //Generate a request:
        SDGRequest req = new SDGRequest();
        req.SDGTag = sdgTestData.TestSDGName;
        req.ParentRecordID = testdatarecordid;
        req.pageid=1;
        req.pagesize=5;
        
        system.debug('request: ' + JSON.serialize(req));
        //Now invoke normal list:
        SDGResult result = getresult(req);
        system.debug('result: ' + JSON.serialize(result));
        //system.assertEquals(false, result.isError,'TestInvalidSDG: No error expected with valid SDG');
        //system.assertEquals(2, result.filteredrowcount,'TestInvalidSDG: Expected 2 sdgfields as this is a valid SDG');
        
        //Update SDG:
        Sdg__c sdg = [select id, is_valid__c from sdg__c where id = :erlid limit 1];
        sdg.is_valid__c = false;
        update sdg;
        sdg = [select is_valid__c from sdg__c where id = :erlid limit 1];
        
        system.debug('set ' + sdg.id + ' to ' + sdg.is_valid__c + ' - should fail now');
        system.debug(JSON.serialize(sdg));
        SDGResult result2 = getResult(req);
        
        system.assertNotEquals('', result2.ErrorMessage,'Expected error message with is_valid=false');
        
        //system.assertEquals(null, result2.filteredrowcount,'Expected rowcount=0 as this is now invalid sdg');
        system.assertEquals(true, result2.isError,'Expected error with is_valid=false');
        
        Test.stopTest();
    }
    
    
    static testMethod void sdgPreferences()
    {
        
        SDG__c sdgData = new SDG__c();
        sdgData.Name ='All Account123'; 
        sdgData.SDG_Tag__c='All Account';
        sdgData.Show_Icon__c=true;
        sdgData.sObjectName__c='Account';
        sdgData.My_Home__c=true;
        sdgData.Is_Valid__c=true;
        sdgData.MyRecords__c='acc';      
        sdgData.List_View_Name__c='All';
        insert sdgData;
        
        SDG__c sdgData1 = new SDG__c();
        sdgData1.Name ='Account'; 
        sdgData1.SDG_Tag__c='Account';
        sdgData1.Show_Icon__c=true;
        sdgData1.sObjectName__c='Account';
        sdgData1.My_Home__c=true;
        sdgData1.Is_Valid__c=true;
        sdgData1.MyRecords__c='acc';
        insert sdgData1;
        SDG_Field__c sdgf= new SDG_Field__c(
            sdg__c=sdgData.id, APIName__c='Name', Color__c='Red'
        ); 
        SDG_Field__c sdgf1= new SDG_Field__c(
            sdg__c=sdgData1.id, APIName__c='Name', Color__c='Red'
        ); 
        insert sdgf1;
        
        Sdg_preferences__c pref = new sdg_preferences__c();
        pref.User__c = UserInfo.getUserId();
        pref.Filters__c = '[{"SDGFieldID":"a023i00000AFG8vAAH","FilterValue":"Sector 63","FilterOperator":"includes"}]';
        pref.sdgKey__c = 'All Account';
        insert pref;
        
        sdg sdgObj = new sdg('contact','Account','Contact','Name!=null','ORDER BY NAME', 'All Account');
        
        Test.startTest();
        
        sdgPreferences.GenerateRequestWithFilters(sdgObj,'TestId','SDG_tag');
        sdgPreferences.getPreference('Account');
        sdgPreferences.deletePreference('All Account');
        
        Test.stopTest();
    }
    static testMethod void testgetMyTeamFilter()
    {
        Profile prof = [Select Id from profile where Name='System Administrator'];
        User user = new User();
        user.firstName = 'Navtest';
        user.lastName = 'User';
        user.profileId = prof.Id;
        user.username = 'NavtestUser@test.com';
        user.email = 'NavtestUser@test.com';
        user.EmailEncodingKey = 'ISO-8859-1'; 
        user.Alias = 'Navtest';  
        user.TimeZoneSidKey = 'America/Los_Angeles';  
        user.LocaleSidKey = 'en_US'; 
        user.LanguageLocaleKey = 'en_US'; 
        insert user;
        
        SDG__c sdgData = new SDG__c();
        sdgData.Name ='All Account123'; 
        sdgData.SDG_Tag__c='All Account';
        sdgData.Show_Icon__c=true;
        sdgData.sObjectName__c='Account';
        sdgData.My_Home__c=true;
        sdgData.Is_Valid__c=true;
        sdgData.List_View_Name__c='All';
        sdgData.My_Teams_Records__c = 'OwnerId IN (SELECT Id FROM User WHERE firstName =\'<<firstName>>\')';
		
        insert sdgData;
        SDG_Field__c sdgf= new SDG_Field__c(sdg__c=sdgData.id, APIName__c='Name', Color__c='Red'); 
        insert sdgf;
        Sdg_preferences__c pref = new sdg_preferences__c();
        pref.User__c = UserInfo.getUserId();
        pref.Filters__c = '[{"SDGFieldID":"a023i00000AFG8vAAH","FilterValue":"Sector 63","FilterOperator":"includes"}]';
        pref.sdgKey__c = 'All Account';
        insert pref;
        
        SDG__c sdgobj = new SDG__c();
        sdgobj.Name ='All Deal'; 
        sdgobj.SDG_Tag__c='All Deal';
        sdgobj.sObjectName__c='Account';
        sdgobj.Is_Valid__c=true;
        sdgobj.My_Teams_Records__c = 'ID IN (SELECT Id FROM User WHERE firstName =\'<<firstName>>\')';
        insert sdgobj;
        SDG_Field__c sdgfobj= new SDG_Field__c(sdg__c=sdgobj.id, APIName__c='Name', Color__c='Red'); 
        insert sdgfobj;
        Test.startTest();
        //System.assertNotEquals('', sdgController.getMyTeamFilter(sdgData.My_Teams_Records__c));
        System.assertEquals('All Deal', sdgobj.SDG_Tag__c);
        sdgController.getMyTeamFilter(sdgobj.My_Teams_Records__c);
        sdgController.getSdgPreference(sdgData.SDG_Tag__c);
        system.runAs(user){
            sdgController.getMyTeamFilter(sdgData.My_Teams_Records__c);
        }
        Test.stopTest();
    }
    static testMethod void testsaveUpdatedRecords()
    {
    
        Account accobj =  new Account();
        accobj.Name ='TestNav';
        accobj.RecordTypeId =  Schema.sObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
        insert accobj;
        
        SDG__c sdgData = new SDG__c();
        sdgData.Name ='All Account123'; 
        sdgData.SDG_Tag__c='All Account';
        sdgData.sObjectName__c='Account';
        sdgData.Is_Valid__c=true;
        sdgData.Enable_Inline_Edit__c = true;
        insert sdgData;
        
        SDG_Field__c sdgfield = new SDG_Field__c(sdg__c=sdgData.id, APIName__c='Name', Color__c='Red'); 
        insert sdgfield;
        SDG_Field__c sdgfield2 = new SDG_Field__c(sdg__c=sdgData.id, APIName__c='Industry', Color__c='Red'); 
        insert sdgfield2;
        SDG_Field__c sdgfield3 = new SDG_Field__c(sdg__c=sdgData.id, APIName__c='AnnualRevenue', Color__c='Red'); 
        insert sdgfield3;
         SDG_Field__c sdgfield4 = new SDG_Field__c(sdg__c=sdgData.id, APIName__c='Name', Color__c='Red'); 
        insert sdgfield4;
        
        String innerData = '{"recordTypeId":"'+accobj.RecordTypeId+'","fields":{"'+sdgfield.ID+'":{"fieldName":"Name","fieldType":"STRING","updatedValue":"Test  Institution1"}}}';
        Map<Object, Object> fieldMap = new Map<Object, Object>{'fieldName' => 'Name', 'fieldType' => 'STRING', 'updatedValue' => 'Test Com'};
		Map<Object, Object> fieldMap2 = new Map<Object, Object>{'fieldName' => 'Industry', 'fieldType' => 'Picklist', 'updatedValue' => 'Banking'};
        Map<Object, Object> fieldMap3 = new Map<Object, Object>{'fieldName' => 'AnnualRevenue', 'fieldType' => 'Currency', 'updatedValue' => 18};
        Map<Object, Object> fieldMap4 = new Map<Object, Object>{'fieldName' => 'Name', 'fieldType' => 'STRING', 'updatedValue' => ''};



        Map<Object, Object> fieldsMap = new Map<Object, Object>();
		fieldsMap.put(sdgfield.ID,fieldMap);    
        fieldsMap.put(sdgfield2.ID,fieldMap2);
        fieldsMap.put(sdgfield3.ID,fieldMap3);
        fieldsMap.put(sdgfield4.ID,fieldMap4);
        Map<Object, Object> innerObjMap = new Map<Object, Object>{'recordTypeId' => accobj.RecordTypeId, 'fields' => fieldsMap};
        Map<String, Object> updatedRecordsMap = new Map<String, Object>{accobj.Id => innerObjMap};
        System.debug('updatedRecordsMap><>>'+updatedRecordsMap);
        Test.startTest();
        Test_sdgRequestMock fakeResponse = new Test_sdgRequestMock();
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        sdgController.saveUpdatedRecords(sdgData.sObjectName__c,sdgData.SDG_Tag__c,updatedRecordsMap);
        System.assertEquals('All Account', sdgData.SDG_Tag__c); // added for security issues PEv4.7 by Aditya on 22 March 2021
        Test.stopTest();
    }
   
public class updatedValue {
	public Rows rows { get; set; } 

}
public class Rows {
	public RowId rowId { get; set; } 

}
public class RowId {
	 public string recordTypeId { get; set; }
	public Fields fields { get; set; } 

}
public class Fields {
	public SDGFieldId SDGFieldId{ get; set; } 

}
public class SDGFieldId {
 public string fieldName { get; set; }
 public string fieldType { get; set; }
 public string updatedValue { get; set; }
 public string multiSelect { get; set; }

}
    
}