unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Navatar_Setup__c/Navatar_Setup__c.object-meta.xml
<CustomObject>
    <label>Navatar Setup</label>
    <nameField>
        <displayFormat>NS - {0000000000}</displayFormat>
        <label>Navatar Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/fields/Admin_Setting__c.field-meta.xml
<CustomField>
    <fullName>Admin_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Setting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CTS_Activity__c.field-meta.xml
<CustomField>
    <fullName>CTS_Activity__c</fullName>
    <label>CTS Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Old Institution Only</fullName>
            </value>
            <value>
                <fullName>Old and New Institutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CTS_Advanced__c.field-meta.xml
<CustomField>
    <fullName>CTS_Advanced__c</fullName>
    <label>CTS Advanced</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact Only</fullName>
            </value>
            <value>
                <fullName>Contact and Institution</fullName>
            </value>
            <value>
                <fullName>Contact, Institution and Custom Object</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Test_ContactTransferSettingsSetup_Ctlr.cls
@isTest
public class Test_ContactTransferSettingsSetup_Ctlr{
    public static testMethod void Test_ContactTransferSettingsSetup() {
        
    try {
            string np = CommonUtility.strNameSpacePrefix; 
            Navatar_Setup__c navSetup= new Navatar_Setup__c();           
            navSetup.admin_setting__c =  true;
            navSetup.cts_activity__c = 'Old Institution Only';
            navSetup.cts_advanced__c = 'Contact and Insitution';
            insert navSetup;
            
            ContactTransferSettingsSetup_Ctlr dclSetup= new  ContactTransferSettingsSetup_Ctlr();
            dclSetup.onEditContTransferSetup();
            dclSetup.onCancel();
            
            Account parentAccount = new Account();
            parentAccount.Name = 'SunMicro Group';
            insert parentAccount;
            
            String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' And Name = 'Company'].Id;
            
            Account acc = new Account();
            acc.Name = 'AIS Group';
            acc.RecordTypeId = recdTypeId;
            acc.ParentId = parentAccount.id;
            insert acc; 
            
            Contact cont= new Contact();
            cont.firstname ='john';
            cont.lastname = 'smith';
            cont.accountid = acc.id;
            insert cont;
            
            Test.startTest();
           
            // Null Web Service mock implementation
            System.Test.setMock(WebServiceMock.class, new MetadataServiceTest.WebServiceMockImpl());
            
            // Only required to workaround a current code coverage bug in the platform
            MetadataService metaDataService = new MetadataService();
            
            // Invoke operations         
            MetadataService.MetadataPort metaDataPort = new MetadataService.MetadataPort();
            metaDataPort.listMetadata(null, null);
            metaDataPort.updateMetadata(null);
                       
            dclSetup.onSaveContTransferSetting();            
            dclSetup.updateContactLayout(true);
            
            Test.stopTest();
                        
        } catch (Exception e) {
            System.assert(false, 'Exception ' + e);
        }
    }
    
    
    public static testMethod void Test_ContactTransferSettingsSetup2() {
        
    try {
            string np = CommonUtility.strNameSpacePrefix; 
            Navatar_Setup__c navSetup= new Navatar_Setup__c();           
            navSetup.admin_setting__c =  true;
            navSetup.cts_activity__c = 'Old Institution Only';
            navSetup.cts_advanced__c = 'Contact and Insitution';
            insert navSetup;
            
            ContactTransferSettingsSetup_Ctlr dclSetup= new  ContactTransferSettingsSetup_Ctlr();
            dclSetup.onEditContTransferSetup();
            dclSetup.onCancel();
            dclSetup.isEnbleContTransferSetup = false;
            
            Account parentAccount = new Account();
            parentAccount.Name = 'SunMicro Group';
            insert parentAccount;
            
            String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' And Name = 'Company'].Id;
            
            Account acc = new Account();
            acc.Name = 'AIS Group';
            acc.RecordTypeId = recdTypeId;
            acc.ParentId = parentAccount.id;
            insert acc; 
            
            Contact cont= new Contact();
            cont.firstname ='john';
            cont.lastname = 'smith';
            cont.accountid = acc.id;
            insert cont;
            
            Test.startTest();
            // Null Web Service mock implementation
            System.Test.setMock(WebServiceMock.class, new MetadataServiceTest.WebServiceMockImpl());
            
            // Only required to workaround a current code coverage bug in the platform
            MetadataService metaDataService = new MetadataService();
            
             // Invoke operations         
            MetadataService.MetadataPort metaDataPort = new MetadataService.MetadataPort();
            metaDataPort.listMetadata(null, null);
            metaDataPort.updateMetadata(null);
            dclSetup.onSaveContTransferSetting();
            
            dclSetup.updateContactLayout(true);
            
            Test.stopTest();
                        
        } catch (Exception e) {
            System.assert(false, 'Exception ' + e);
        }
    }
}