unpackaged/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>A Company is an operating asset that is a potential acquisition / investment target.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Institution.recordType-meta.xml
<RecordType>
    <fullName>Institution</fullName>
    <active>true</active>
    <label>Institution</label>
</RecordType>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Fund_Type__c.field-meta.xml
<CustomField>
    <fullName>Fund_Type__c</fullName>
    <label>Fund Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fund</fullName>
            </value>
            <value>
                <fullName>Fund of Funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/Fundraising__c.object-meta.xml
<CustomObject>
    <label>Fundraising</label>
    <nameField>
        <label>Fundraising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraisings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising__c/fields/Portfolio_Company__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraisings</relationshipLabel>
    <relationshipName>Fundraising_Company</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/Fundraising_Contact__c.object-meta.xml
<CustomObject>
    <label>Fundraising Contact</label>
    <nameField>
        <displayFormat>FC - {0}</displayFormat>
        <label>Fundraising Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fundraising Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Fundraising_Contact__c/fields/Fundraising__c.field-meta.xml
<CustomField>
    <fullName>Fundraising__c</fullName>
    <label>Fundraising</label>
    <referenceTo>Fundraising__c</referenceTo>
    <relationshipLabel>Fundraising Contacts</relationshipLabel>
    <relationshipName>Fundraising_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Test_SetPrimaryContactCTRL.cls
@isTest
private class Test_SetPrimaryContactCTRL
{
    public static testMethod void method1()
    {
        Account objacc=new Account();
        objacc.Name='test account';
        insert objacc;
        System.assertEquals('test account', objacc.Name); 
        
        Fund__c fundObj = new Fund__c(Name='testFund',Fund_Type__c='Fund');
        insert fundObj;  
        System.assertEquals('testFund', fundObj.Name); // (PE3.5, SK, 9Aug2017)   
        
        
        contact con = new contact();
        con.lastName = 'Test last Contact'; 
        con.firstname = 'Test First Name'; 
        con.HasOptedOutOfEmail=false;  
        con.MailingCity ='Test City'; 
        con.MailingCountry='Test country';  
        con.MailingPostalCode = '102010';
        con.MailingState = 'Test State';
        con.MailingStreet='Test street';
        con.Description='test hello how are you';
        con.Fax='012423';
        con.Phone = '01245263';
        con.otherCity = 'test other city';
        con.otherCountry='Test other country';  
        con.otherPostalCode = '1020101';
        con.otherState = 'Test other State';
        con.otherStreet='Test other street'; 
        con.accountid=objacc.id;
        insert con;
        System.assertEquals('Test last Contact', con.LastName);
        
        
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        
        Account acc = new Account(Name='test Account',recordtypeid=AccountRecordTypeInfo.get('Company').getRecordTypeId());
        insert acc;
        System.assertEquals('test Account', acc.Name); 
        
        // Institution replaced with Individual Investor by Sudhanshu on 06-11-2024
        Account Acc_inst = new Account(Name='test1',recordtypeid=AccountRecordTypeInfo.get('Individual Investor').getRecordTypeId());
        insert Acc_inst;
        System.assertEquals('test1', Acc_inst.Name); 
        
        
        Fundraising__c objFR = new Fundraising__c(Name= 'Test Fundraising',Portfolio_Company__c=acc.id,Fund_Name__c=fundObj.id,Legal_Name__c=Acc_inst.id);      
        insert objFR;   
        System.assertEquals('Test Fundraising', objFR.Name); 
        
        Fundraising_Contact__c FC=new   Fundraising_Contact__c();
        FC.Contact__c=con.id;
        FC.Fundraising__c=objFR.id;   
        insert FC;
        System.assertNotEquals('Test last Contact', FC.Name); 
        
        list<Fundraising_Contact__c > lstfr = new list<Fundraising_Contact__c >(); 
        lstfr.add(FC);
        
        Apexpages.currentPage().getParameters().put('id', objFR.id);
        SetPrimaryContactCTRL objMEF = new SetPrimaryContactCTRL(new ApexPages.StandardSetController(lstfr));
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FC);
        SetPrimaryContactCTRL testAccPlan = new SetPrimaryContactCTRL(sc);
    }
    
}