unpackaged/main/default/objects/Navatar_Setup__c/Navatar_Setup__c.object-meta.xml
<CustomObject>
    <label>Navatar Setup</label>
    <nameField>
        <displayFormat>NS - {0000000000}</displayFormat>
        <label>Navatar Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/fields/Admin_Setting__c.field-meta.xml
<CustomField>
    <fullName>Admin_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Setting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/IIS__c.field-meta.xml
<CustomField>
    <fullName>IIS__c</fullName>
    <label>IIS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/TestIndividualInvestorSetup_Ctlr.cls
@isTest
public class TestIndividualInvestorSetup_Ctlr
{
    static TestMethod void TestMethod1()
    {
        Navatar_Setup__c NS =  new Navatar_Setup__c();
        NS.admin_setting__c = true;
        NS.IIS__c = 'Contact:Phone,Contact:Fax,Account:Name;Account:AccountSource,Account:Fax,Account:Phone';
        insert NS;
        System.assertEquals('Contact:Phone,Contact:Fax,Account:Name;Account:AccountSource,Account:Fax,Account:Phone', NS.IIS__c); // (PE3.5, SK, 8Aug2017)
        
        IndividualInvestorSetup_Ctlr IIS = new IndividualInvestorSetup_Ctlr();
        IIS.revertToDefaultAct();
        IIS.saveIISetupAct();
    }
}