unpackaged/main/default/objects/SDG__c/fields/All_Rows__c.field-meta.xml
<CustomField>
    <fullName>All_Rows__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Retrieve all rows - including archived and deleted records. Generally leave as false unless there&#39;s a specific need.</inlineHelpText>
    <label>All Rows</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/DisableSharing__c.field-meta.xml
<CustomField>
    <fullName>DisableSharing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Disable Sharing rules (ie run &#39;Without Sharing&#39;)</inlineHelpText>
    <label>Disable Sharing Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Enable_Inline_Edit__c.field-meta.xml
<CustomField>
    <fullName>Enable_Inline_Edit__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use this field to enable/disbale inline editing in the SDG.</description>
    <label>Enable Inline Edit</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Enable_Manage_Field__c.field-meta.xml
<CustomField>
    <fullName>Enable_Manage_Field__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable Manage Fields</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <inlineHelpText>Define SOQL filter here - no AND or WHERE necessary - this will always be applied</inlineHelpText>
    <label>Filter</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/List_View_Name__c.field-meta.xml
<CustomField>
    <fullName>List_View_Name__c</fullName>
    <description>Use this field to specify the API Name of the Lightning List View. The SDG will then inherit the filter conditions applied for that List View.
Note: For an SDG, user can either fill &#39;Filter&#39; or &#39;List View Name&#39;.</description>
    <label>List View Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/My_Home__c.field-meta.xml
<CustomField>
    <fullName>My_Home__c</fullName>
    <defaultValue>false</defaultValue>
    <label>My Home</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/My_Teams_Records__c.field-meta.xml
<CustomField>
    <fullName>My_Teams_Records__c</fullName>
    <description>Use this field to specify the condition to display the records where logged-in user&#39;s team is associated with the record. E.g.: If there is a Contact’s SDG and the logged-in user wants to view the contacts where all his/her team members are the owners then write query as “(Owner.Id IN (SELECT Id FROM User WHERE Team__c = &#39;&lt;&lt;Team__c&gt;&gt;&#39;))”.
This will be further used by Universal Filter to display the desired filtered result.</description>
    <label>My Teams Records</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/MyRecords__c.field-meta.xml
<CustomField>
    <fullName>MyRecords__c</fullName>
    <description>Use this field to specify the condition to display the records where logged-in user is associated with the record. E.g.: If there is a Contact’s SDG and the logged in user wants to view the contacts where he/she is the Owner along with all the contacts where he/she is the Account Owner, then write query as “(Owner.ID = &lt;&lt;User.Id&gt;&gt; OR Account.OwnerId= &lt;&lt;User.Id&gt;&gt;)”.
This will be further used by Universal Filter to display the desired filtered result.</description>
    <label>My Records</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Related_Association_Query__c.field-meta.xml
<CustomField>
    <fullName>Related_Association_Query__c</fullName>
    <label>Related Association Query</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Remember_Filter__c.field-meta.xml
<CustomField>
    <fullName>Remember_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remember Filter</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG__c/fields/Show_Icon__c.field-meta.xml
<CustomField>
    <fullName>Show_Icon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Icon</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Action__c/SDG_Action__c.object-meta.xml
<CustomObject>
    <label>Sortable Data Grid Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SDG_Action__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Row</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
            <value>
                <fullName>Row Button</fullName>
            </value>
            <value>
                <fullName>List Button</fullName>
            </value>
            <value>
                <fullName>List Multi</fullName>
                <label>List Multi-Select</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SDG_Action__c/fields/Event_Payload__c.field-meta.xml
<CustomField>
    <fullName>Event_Payload__c</fullName>
    <inlineHelpText>Payload for the event.  For LIST actions, will automatically replace #parentrecordId# with valid id.  For ROW actions, will automatically replace fieldnames with # at beginning and end with the corresponding values.  example: 
{
   &quot;recordId&quot;: &quot;#Id#&quot;
}</inlineHelpText>
    <label>Event Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG_Action__c/fields/Requires_Createable__c.field-meta.xml
<CustomField>
    <fullName>Requires_Createable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only show this action if the user is required to have Create rights on the sObject on the grid.</inlineHelpText>
    <label>Requires Createable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Action__c/fields/Requires_Deletable__c.field-meta.xml
<CustomField>
    <fullName>Requires_Deletable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only show this action if the user is required to have Delete rights on the sObject on the grid.</inlineHelpText>
    <label>Requires Deletable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Action__c/fields/Requires_Editable__c.field-meta.xml
<CustomField>
    <fullName>Requires_Editable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only show this action if the user is required to have Edit rights on the sObject on the grid.</inlineHelpText>
    <label>Requires Editable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Action__c/fields/SDG__c.field-meta.xml
<CustomField>
    <fullName>SDG__c</fullName>
    <label>SDG</label>
    <referenceTo>SDG__c</referenceTo>
    <relationshipLabel>Sortable Data Grid Actions</relationshipLabel>
    <relationshipName>SDG_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/SDG_Field__c.object-meta.xml
<CustomObject>
    <label>Sortable Data Grid Field</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SDG_Field__c/fields/Field_Style__c.field-meta.xml
<CustomField>
    <fullName>Field_Style__c</fullName>
    <inlineHelpText>Use a custom renderer with special behaviours</inlineHelpText>
    <label>Custom Renderer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Age</fullName>
            </value>
            <value>
                <fullName>Summarize:Total</fullName>
            </value>
            <value>
                <fullName>Summarize:Min</fullName>
            </value>
            <value>
                <fullName>Summarize:Max</fullName>
            </value>
            <value>
                <fullName>Summarize:Average</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/fields/Filter_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Filter_Sequence__c</fullName>
    <description>Use this field to assign the sequence number of the field used in the Universal filter. This assignment will govern the filtering of data in the SDG for this field, when user filters value for the assigned numbered field from Universal filter. For e.g: If the industry field in the SDG is assigned Filter Sequence 1, because in Universal filter Industry field is at first position. On selecting &#39;Technology&#39; for Industry in Universal filter, SDG will also gets filtered data where Industry value equals to &#39;Technology&#39; according to filter sequence assignment.</description>
    <label>Filter Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/fields/Grouping_Query__c.field-meta.xml
<CustomField>
    <fullName>Grouping_Query__c</fullName>
    <description>Use this field to write an aggregate SOQL query to display count/sum/min/max/avg in a column.
E.g.: “Select count(Id), AccountId from Contact where AccountId in &lt;&lt;AccountId&gt;&gt; group by AccountId”
This query will specify number of Contacts for an Account.</description>
    <label>Grouping Query</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/fields/Hide_Filter__c.field-meta.xml
<CustomField>
    <fullName>Hide_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Filter</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/fields/is_valid_field__c.field-meta.xml
<CustomField>
    <fullName>is_valid_field__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Enable/Disable field display.  If the package thinks there&#39;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SDG_Field__c/fields/sdg__c.field-meta.xml
<CustomField>
    <fullName>sdg__c</fullName>
    <label>sdg</label>
    <referenceTo>SDG__c</referenceTo>
    <relationshipName>SDGFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/sdgDataProviderNative.cls
/*
* Copyright (c) 2018, salesforce.com, inc.
* All rights reserved.
* SPDX-License-Identifier: BSD-3-Clause
* For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
global with sharing class sdgDataProviderNative implements sdgIDataProvider {
    global static Boolean isUserSelectable()
    {
        return false;
    }
    global static SDGResult getData(SDG CoreSDG, SDGRequest request)
    {
        
        SDGResult result =  sdgQueryEngine.getSDGResultRaw(CoreSDG, request);
        return result;
    }
    
    global   SDG LoadSDG(String SDGTag, String ParentRecordId)
    {
        SDG CoreSDG = null;
        Set<String> relatedIdsset;
        sdgSecurity.CanQuery('sdgDataProviderNative:LoadSDG', 'SDG__c', 'sobjectname__c, parent_field_name__c, filter__c, default_sort__c, is_valid__c, All_Rows__c, DisableSharing__c', 'Id', sdgNamespaceUtility2.GetNamespace(), true);
        sdgSecurity.CanQuery('sdgDataProviderNative:GetSDGActions' , 'SDG_Action__c', 'event__c, action_order__c, Requires_Createable__c, requires_deletable__c, Requires_Editable__c, Action_Type__c, Event_Payload__c, Icon__c', 'id,name', sdgNamespaceUtility2.GetNamespace(), true);
        sdgSecurity.CanQuery('sdgDataProviderNative:GetSDGFields', 'SDG_Field__c', 'apiname__c,  FieldOrder__c, Field_Style__c, Hide_Filter__c, Override_Label__c', 'id,name', sdgNamespaceUtility2.GetNamespace(), true);
        //Related_Association_Query__c field add in in Phase3 CR by Akash(28-11-2019).
        // My_Teams_Records__c,Grouping_Field_API__c in sdg and  Filter_sequence__c in SDGFields  fields added in v1.3 Phase4 at (29-01-2020).
        //Added Manage_Field in query
        List<SDG__c> sdgs= [select id, Show_Icon__c, MyRecords__c, my_home__c, Remember_Filter__c, Highlight_Colors__c, sobjectname__c, parent_field_name__c, filter__c, List_View_Name__c,  default_sort__c, is_valid__c, All_Rows__c, DisableSharing__c, Related_Association_Query__c, My_Teams_Records__c,Grouping_Field_API__c,Enable_Inline_Edit__c,Enable_Manage_Field__c,
                            (select id, name, event__c, Requires_Createable__c, Requires_Editable__c, requires_deletable__c, Action_Type__c, Event_Payload__c, Icon__c, action_order__c  from sdg_actions__r), 
                            (select id, name, apiname__c,  FieldOrder__c, Field_Style__c, Hide_Filter__c, Override_Label__c, URL__c, grouping_query__c, Is_Hidden__c,color__c,Parent_Field_Name_Grouping__c,Filter_sequence__c, Image_field_API__c from SDGFields__r where is_valid_field__c =true) 
                            from SDG__c where SDG_Tag__c = :SDGTag ]; // Akash added URL__c and grouping_query__c field
        if (sdgs.size()!=1)
        {
            throw new SDGException('sdgDataProviderNative:LoadSDG: Invalid number of SDG results for name: ' + SDGTag + '. retrieved: ' + sdgs.size());
        }
        else
        {
            //Now we can load this:
            SDG__c e;
            e = sdgs[0];
            
            // logic to populate filter dynamically ~Akash
            if(e.List_View_Name__c != null && e.List_View_Name__c != ''){
                //As discussed with Anurag, commenting if else condition from code listview filter will always override filter field(20190521)
                /*if(e.filter__c != null && e.filter__c != ''){
					e.filter__c = e.filter__c + ' AND (' + getFilterString(e.List_View_Name__c, e.sobjectname__c) + ' ) ';
			}
			else{*/
                e.filter__c = getFilterString(e.List_View_Name__c, e.sobjectname__c);
                //}
            }
            // Check Related_Association_Query__c field the get result and replace with '<<relatedids>>' in Phase3 CR by Akash(28-11-2019). 
            if(String.isNotBlank(e.Related_Association_Query__c) && String.isNotBlank(e.Filter__c) && e.Filter__c.containsIgnoreCase('<<relatedIds>>')){
               sdgDatabase.setIdsString  = generateLikeClause(e.Related_Association_Query__c); //For Using store Related Association Query in v1.3 phase-4 at 23-04-2020 By Rahulk
                e.Filter__c = e.Filter__c.tolowercase().replace('<<relatedids>>',' :setIdsString');
                e.Filter__c =  '('+ e.Filter__c+')'; //Bug fixing(00028263) in Phase4 v1.3 CR by Rahulk(17-03-2020). 
            }
            if(String.isNotBlank(e.Filter__c)){
                e.Filter__c =  '('+ e.Filter__c+')'; //Bug fixing(00028263) in Phase4 v1.3 CR by Rahulk(17-03-2020).
            }
            
            //Replace userId expression with logged in user id
            if(e.My_Home__c && String.isNotBlank(e.MyRecords__c)){ // Placed here by Himanshu, for MyRecord Sub Query issue
                if(String.isBlank(e.filter__c)){
                    e.filter__c = '('+e.MyRecords__c.replaceAll('<<User.Id>>',UserInfo.getUserId())+')';
                }else{
                    e.filter__c = e.filter__c+ ' AND ('+e.MyRecords__c.replaceAll('<<User.Id>>',UserInfo.getUserId())+')';
                }
            }
            system.debug('sdgDataProviderNative:LoadSDG:e.filter__c ' + e.filter__c);
            if (!e.is_valid__c)
            {
                system.debug('This is an invalid SDG');
                throw new SDGException('SDG: ' + SDGTag + ' is marked as invalid');
            }
            //Replace record id expression with parentId change for v1.3 Phase 4 at (29-01-2020)
            if(String.isNotBlank(e.Filter__c) && String.isNotBlank(ParentRecordId)){
                e.Filter__c = e.Filter__c.tolowercase().replace('<<recordid>>',ParentRecordId);            
            }
            
            CoreSDG = new SDG(e.sObjectName__c, e.Parent_Field_Name__c,  e.sobjectname__c,  e.Filter__c,  e.Default_Sort__c, e.Id, e.All_Rows__c );
            CoreSDG.internalData.DisableSharing = e.DisableSharing__c;
            CoreSDG.sdgId = e.Id;
            CoreSDG.highlightString = e.Highlight_Colors__c;
            CoreSDG.rememberFilter = e.Remember_Filter__c;
            CoreSDG.showIcon = e.Show_Icon__c;
            CoreSDG.myRecords = e.MyRecords__c;
            coreSDG.sdgGroupingField = e.Grouping_Field_API__c;
            CoreSDG.myTeamsRecords = e.My_Teams_Records__c; //  My Team's Records added in v1.3 at (29-01-2020)
            //coreSDG.highlightString = e.Highlight_row__c;
            //Check SDG edit permission for Manage_Field
            CoreSDG.enableManageField = (Schema.sObjectType.SDG_Field__c.isAccessible());
            CoreSDG.isEnableManageField = e.Enable_Manage_Field__c;
            Schema.SObjectType targetType = Schema.getGlobalDescribe().get(CoreSDG.sObjectName);
            if (targetType==null)
            {
                system.debug('sdgDataProviderNative:LoadSDG: invalid sObjectName');
                throw new SDGException('sdgDataProviderNative: Invalid sObjectName provided - are you missing a namespace?');
            }
            Id CoreSDGId = CoreSDG.InternalData.sUniqueKey;
            // #9 - Inline edit functionality
            // Add value in  sdg response in Phase-4(InlineEdit) at 14-02-2020
            CoreSDG.isEditableSDG = e.Enable_Inline_Edit__c;
            List<SDG_Field__c> fields = e.sdgfields__r;
            if (fields!=null)
                CoreSDG.SDGFields = GetSDGFields(fields, targetType);
            
            List<SDG_Action__c> actions = e.sdg_actions__r;
            if (actions!=null)
                CoreSDG.SDGActions = GetSDGActions(actions, e.sObjectName__c);
        }
        
        return coreSDG;
    }
    
    private  List<SDGAction> GetSDGActions(List<SDG_Action__c> actions, String sObjectName)
    {
        
        
        List<SDGAction> results = sdgMapper.MapToSDGActions(sObjectName, actions);
        results.sort();
        return results;
    }
    private  List<SDGField> GetSDGFields(List<sdg_field__c> fields, Schema.SObjectType targetType )
    {
        
        if (fields.size()==0)
        {
            throw new SDGException('sdgDataProviderNative:GetSDGFields: SDG has no fields');
        }
        
        //Now convert to fields - do FLS checks as well
        List<SDGField> results = sdgMapper.MapToSDGFields(targetType, fields, true);
        results.sort();
        return results;
        
    }
    
    
    // This method is gives us Where clause of List view based on list view Id and sObject.
    //logic to populate filter dynamically ~Akash
    
    private string getFilterString(String listViewName, String objectName){
        
       String sessionId;
        if(Test.isRunningTest()){
            sessionId = UserInfo.getSessionId();
        }else{
            String  content = Page.PageWithSessionId.getContent().toString();
            Integer s = content.indexOf('Start_Of_Session_Id') + 'Start_Of_Session_Id'.length(),
            e = content.indexOf('End_Of_Session_Id');
           sessionId = content.substring(s, e);
        }
        
        Http http = new Http();
        HttpRequest request;
        HttpResponse response;
        String queryStr;
        String filterStr = '';
        if(String.isBlank(listViewName)){
            filterStr = '';
        }else{
            queryStr = '';
            List<ListView> lstViewDetails =[SELECT Id, DeveloperName FROM ListView where DeveloperName =: listViewName];
            if(lstViewDetails.size() > 0){
                request = new HttpRequest();
                request.setEndpoint(URL.getSalesforceBaseUrl().toExternalForm()+'/services/data/v44.0/sobjects/'+objectName+'/listviews/'+lstViewDetails[0].Id+'/describe');
                request.setMethod('GET');
                request.setHeader('Authorization', 'OAuth ' + sessionId);        
                request.setHeader('Authorization', 'Bearer ' + sessionId); 
                response = http.send(request);
                if (response.getStatusCode() == 200) {
                    System.debug('response:'+ response.getBody());
                    Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                    if(resMap.containsKey('query') && String.isNotBlank((String)resMap.get('query'))){
                        queryStr = (String)resMap.get('query');
                        if(queryStr.containsIgnorecase('WHERE')){
                            filterStr = queryStr.substring(queryStr.indexOf('WHERE') + 6, queryStr.indexOf('ORDER BY'));
                        }
                        // Code added by sameer Reason: My data and all data filtering.
                        if((string)resMap.get('scope') == 'mine'){
                            string myFilter = 'ownerId = \''+userInfo.getUserId()+'\'';
                            if(string.isNotBlank(filterStr)){
                                filterStr = '('+filterStr+') AND '+myFilter;
                            }
                            else{
                                filterStr = myFilter;
                            }
                        }
                    }
                }
            }
        }
        return filterStr;
    }
    /*
       Method Modified for Bulk data of related Association for bug fixing (00028538) in v1.3 Phase-4 by Rahulk
	*/
    public static set<string> generateLikeClause(String queryStr){
        Map<id,Sobject> sObjMap = new Map<id,Sobject>(Database.query(queryStr));
        Set<String> relatedIds = new Set<String>();
        
        for(Id objId : sObjMap.keySet()){           
                relatedIds.add('%'+objId+'%');            
        }
        if(relatedIds.size() == 0){
            relatedIds.add('%000000000000000000%');
        }
        system.debug('relatedIds>>>>>>>>'+relatedIds);
        return relatedIds;
    }    
}