unpackaged/main/default/objects/Org_Setting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TestCustomMetadataService.cls
@isTest(SeeAllData='true')
public class TestCustomMetadataService
{
    static testMethod void testMethod1()
    {
        SObject orgEmailSetting = [SELECT IsActive__c,label,developername FROM Org_Setting__mdt where developername ='Co_Inv_Setting' limit 1];
        
        MetadataService.CustomMetadata check = CustomMetadataService.toCustomMetadata(orgEmailSetting);
        CustomMetadataService.createService();
        MetadataService.SaveResult objSaveResult = new MetadataService.SaveResult();
        objSaveResult.success=true;
        System.assertEquals(true, objSaveResult.success); // (PE3.5, SK, 9Aug2017)
        
        CustomMetadataService.handleSaveResults(objSaveResult);
    }
}