unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/Navatar_Setup__c.object-meta.xml
<CustomObject>
    <label>Navatar Setup</label>
    <nameField>
        <displayFormat>NS - {0000000000}</displayFormat>
        <label>Navatar Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Navatar Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Navatar_Setup__c/fields/Admin_Setting__c.field-meta.xml
<CustomField>
    <fullName>Admin_Setting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Setting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/CI_Fund_ID__c.field-meta.xml
<CustomField>
    <fullName>CI_Fund_ID__c</fullName>
    <label>CI Fund ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Navatar_Setup__c/fields/IIS__c.field-meta.xml
<CustomField>
    <fullName>IIS__c</fullName>
    <label>IIS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/TestCoInvestment_Settings_setup_Ctlr.cls
@isTest
public class TestCoInvestment_Settings_setup_Ctlr
{
    @isTest(onInstall=True)
    static void testCoinvestSetup()
    {
        Fund__c fObj = new Fund__c();
        fObj.name = 'TestClassFund';
        insert fObj;
        System.assertEquals('TestClassFund', fObj.Name); // (PE3.5, SK, 9Aug2017)
        
        Navatar_Setup__c NS =  new Navatar_Setup__c();
        NS.admin_setting__c = true;
        NS.IIS__c = 'Contact:Phone,Contact:Fax,Account:Name;Account:AccountSource,Account:Fax,Account:Phone';
        NS.CI_Fund_ID__c = fObj.id;
        insert NS;
        System.assertNotEquals('MI1 test', NS.Name); // (PE3.5, SK, 9Aug2017)
        
        CoInvestment_Settings_setup_Ctlr CSS = new CoInvestment_Settings_setup_Ctlr();
        CSS.editConInvestmentSetup();
        CSS.onSaveCoInvestmentSetup();
    }
}