unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund_Drawdown__c/Fund_Drawdown__c.object-meta.xml
<CustomObject>
    <description>To capture the total amount the fund will draw, which in turn will be split into multiple capital calls</description>
    <label>Fund Drawdown</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>DD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Drawdowns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund_Drawdown__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Drawdown</relationshipLabel>
    <relationshipName>Fund_Drawdown</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/Partnership__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Test_FundSelectionDrawdown.cls
@isTest
public class Test_FundSelectionDrawdown
{
    public static testMethod void testFundSelectionDrawdown()
    {
        Fund__c fnd = new Fund__c(name = 'Test Fund');
        insert fnd;
        Fund_Drawdown__c fndDrdwn = new Fund_Drawdown__c(Fund_Name__c =fnd.id);
        insert fndDrdwn;
        Fund__c fnd1=[select name from Fund__c where id=:fnd.id];
        System.assertEquals('Test Fund',fnd1.name);
        ApexPages.StandardController sc = new ApexPages.StandardController(fndDrdwn);
        FundSelectionDrawdown f = new FundSelectionDrawdown(sc);
        f.evaluate();
        ApexPages.currentPage().getParameters().put('retURL','hksdfsld');
        f.evaluate();
        f.part = new Partnership__c(name='Test Part', Fund__c = fnd.id);
        insert f.part;
        ApexPages.currentPage().getParameters().put('retURL',fnd.id);
        f.evaluate();
        ApexPages.currentPage().getParameters().put('retURL',f.part.id);
        f.evaluate();
        f.redirectFun();
    }
}