unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund_Distribution__c/Fund_Distribution__c.object-meta.xml
<CustomObject>
    <description>To capture the total amount the fund will distribute, which in turn will be split into multiple investor distributions</description>
    <label>Fund Distribution</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>FD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund_Distribution__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Distribution</relationshipLabel>
    <relationshipName>Fund_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/Partnership__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/FundSelectionDistribution.cls
public with sharing class FundSelectionDistribution {

    public Sobject obj;
    public FundSelectionDistribution(ApexPages.StandardController controller) {
        
        obj = controller.getRecord();
        part = new Partnership__c();
    }

    public PageReference evaluate()
    {
        try
        {    
            if(obj.get('Fund_Name__c') != null){
                 string st = string.valueOf(obj.get('Fund_Name__c'));  
                Fund__c f = new Fund__C(id = st);
                return new PageReference('/apex/createDistribution?scontrolCaching=1&id='+st);
            }
            else{
                return null;
            }
           
        }
        catch(System.NullPointerException e)
        {
            system.assert(e.getMessage().contains('de-reference a null object'));
        }
        catch(System.TypeException e)
        {
            system.assert(e.getMessage().contains('Invalid id'));
        }
        catch(System.StringException e)
        {
            system.assert(e.getMessage().contains('Invalid id'));
        }
        return null;
    }

    public Partnership__c part{get;set;}
    
    public PageReference redirectFun(){   
        return new PageReference('/apex/createDistribution?scontrolCaching=1&id='+part.Fund__c);
    }

    //Test meathod
    public static testMethod void testFundSelectionDistribution()
    {
        Fund__c fnd = new Fund__c(name = 'Test Fund');
        if(Schema.sObjectType.Fund__c.isCreateable()){
          insert fnd;
        }
        
        Fund_Distribution__c fndDistribution= new Fund_Distribution__c(Fund_Name__c =fnd.id);
        if(Schema.sObjectType.Fund_Distribution__c.isCreateable()){
          insert fndDistribution;
        }
        
        Fund__c fnd1=[select name from Fund__c where id=:fnd.id];
        System.assertEquals('Test Fund',fnd1.name);
        ApexPages.StandardController sc = new ApexPages.StandardController(fndDistribution);
        FundSelectionDistribution f = new FundSelectionDistribution(sc);
        //f.evaluate();
        ApexPages.currentPage().getParameters().put('retURL','hksdfsld');
        f.evaluate();
        f.part = new Partnership__c(name='Test Part', Fund__c = fnd.id);
        if(Schema.sObjectType.Partnership__c.isCreateable()){
          insert f.part;
       }
        ApexPages.currentPage().getParameters().put('retURL',fnd.id);
        f.evaluate();
        ApexPages.currentPage().getParameters().put('retURL',f.part.id);
        f.evaluate();
        f.redirectFun();
    }
}