unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/Partnership__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/FundSelectionDrawdown.cls
/*********************************************************************************
** Module Name  : FundSelectionDrawdown
** Description  : To redirect the page and exception handling  
** Test Class   : Available
** Throws       : NA
** Calls        : NA
** Organization : Navatar Group
**
** Revision History:-
** Version    Date          Author               Description of Action
** 3.5       2016-07-09   vasudha Tandon     To redirect the page and exception handling
*********************************************************************************/
public with sharing class FundSelectionDrawdown {

    public Sobject obj;
    
    // constructor
    public FundSelectionDrawdown(ApexPages.StandardController controller) {
        obj = controller.getRecord();
        part = new Partnership__c();
    }

    // This method redirects to FundDrawdownNewOverride , handle the null object and invalid exception
    public PageReference evaluate()
    {
        try
        {
            if(obj.get('Fund_Name__c') != null){
                string st = string.valueOf(obj.get('Fund_Name__c'));
                Fund__c f = new Fund__C(id = st);
                return new PageReference('/apex/createDrawdown?scontrolCaching=1&id='+st);
            }
            else{
                return null;
            }            
        }
        catch(System.NullPointerException e)
        {
            system.assert(e.getMessage().contains('de-reference a null object'));
        }
        catch(System.TypeException e)
        {
            system.assert(e.getMessage().contains('Invalid id'));
        }
        catch(System.StringException e)
        {
            system.assert(e.getMessage().contains('Invalid id'));
        }
        return null;
    }

    public Partnership__c part{get;set;}
    
    // when Create Draudown button will click then it rediects to createDrawdown page with fund Id
    public PageReference redirectFun()
    {
        return new PageReference('/apex/createDrawdown?scontrolCaching=1&id='+part.Fund__c);
    }
}