unpackaged/main/default/objects/Capital_Call__c/Capital_Call__c.object-meta.xml
<CustomObject>
    <description>To capture the amount that is called from limited partners for each commitment</description>
    <label>Capital Call</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>CC No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Capital_Call__c/fields/Commitment__c.field-meta.xml
<CustomField>
    <fullName>Commitment__c</fullName>
    <label>Commitment</label>
    <referenceTo>Commitment__c</referenceTo>
    <relationshipLabel>Capital Calls</relationshipLabel>
    <relationshipName>Capital_Calls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Capital_Call__c/fields/Fund_Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Fund_Drawdown__c</fullName>
    <label>Fund Drawdown</label>
    <referenceTo>Fund_Drawdown__c</referenceTo>
    <relationshipLabel>Capital Calls</relationshipLabel>
    <relationshipName>Capital_Calls</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/Commitment__c.object-meta.xml
<CustomObject>
    <label>Commitment</label>
    <nameField>
        <displayFormat>CMT - {000000}</displayFormat>
        <label>Commitment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commitment__c/fields/Limited_Partner__c.field-meta.xml
<CustomField>
    <fullName>Limited_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Limited Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commitment__c/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partnership</label>
    <referenceTo>Partnership__c</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Commitment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund__c/fields/Fund_Type__c.field-meta.xml
<CustomField>
    <fullName>Fund_Type__c</fullName>
    <label>Fund Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fund</fullName>
            </value>
            <value>
                <fullName>Fund of Funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fund_Distribution__c/Fund_Distribution__c.object-meta.xml
<CustomObject>
    <description>To capture the total amount the fund will distribute, which in turn will be split into multiple investor distributions</description>
    <label>Fund Distribution</label>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>FD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund_Distribution__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Distribution</relationshipLabel>
    <relationshipName>Fund_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fund_Drawdown__c/Fund_Drawdown__c.object-meta.xml
<CustomObject>
    <description>To capture the total amount the fund will draw, which in turn will be split into multiple capital calls</description>
    <label>Fund Drawdown</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>DD No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Drawdowns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fund_Drawdown__c/fields/Fund_Name__c.field-meta.xml
<CustomField>
    <fullName>Fund_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund Name</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Drawdown</relationshipLabel>
    <relationshipName>Fund_Drawdown</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Investor_Distribution__c/Investor_Distribution__c.object-meta.xml
<CustomObject>
    <description>To capture the amount that is distributed to limited partners for each commitment</description>
    <label>Investor Distribution</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>ID No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investor Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Investor_Distribution__c/fields/Commitment__c.field-meta.xml
<CustomField>
    <fullName>Commitment__c</fullName>
    <label>Commitment</label>
    <referenceTo>Commitment__c</referenceTo>
    <relationshipLabel>Investor Distributions</relationshipLabel>
    <relationshipName>Investor_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Investor_Distribution__c/fields/Fund_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Fund_Distribution__c</fullName>
    <label>Fund Distribution</label>
    <referenceTo>Fund_Distribution__c</referenceTo>
    <relationshipLabel>Investor Distributions</relationshipLabel>
    <relationshipName>Investor_Distributions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Partnership__c/Partnership__c.object-meta.xml
<CustomObject>
    <label>Partnership</label>
    <nameField>
        <label>Partnership Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Partnership__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Partnerships</relationshipLabel>
    <relationshipName>Partnership</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/Test_MassEmail_CC_ID.cls
@isTest
Private class Test_MassEmail_CC_ID{
     
    static testMethod void mytest()
    {        
        //String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' AND Name = 'Limited Partner'].Id;
        Organization org=new Organization();
        Account acc = new Account(Name = 'test');
        insert acc;
        System.assertEquals('test', acc.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund__c fd=new Fund__c();
        fd.name='fund';
        fd.Fund_Type__c='fund';
        insert fd;
        System.assertEquals('fund', fd.Name); // (PE3.5, SK, 8Aug2017)

        Fund_Distribution__c fdDist=new Fund_Distribution__c();
        fdDist.Fund_Name__c=fd.id;
        insert fdDist;
        System.assertNotEquals('MI1 test', fdDist.Name); // (PE3.5, SK, 8Aug2017)   

        Account acc_Lp = new Account();
        acc_Lp.Name='test1';
        // acc_Lp.recordtypeid=recdTypeId;
        acc_Lp.ParentId = acc.Id;
        insert acc_Lp;
        System.assertEquals('test1', acc_Lp.Name); // (PE3.5, SK, 8Aug2017)
         
        Partnership__c ptrship=new Partnership__c();
        ptrship.Name='ravii';
        ptrship.Fund__c=fd.Id;
        insert ptrship;
        System.assertEquals('ravii', ptrship.Name); // (PE3.5, SK, 8Aug2017)
         
        Commitment__c cmmt=new Commitment__c();
        cmmt.Partnership__c=ptrship.Id;
        cmmt.Limited_Partner__c=acc_Lp.id;
        insert cmmt;
        System.assertNotEquals('MI1test', cmmt.Name); // (PE3.5, SK, 8Aug2017)
        
        Investor_Distribution__c inDist=new Investor_Distribution__c();
        inDist.Fund_Distribution__c=fdDist.Id;
        inDist.Commitment__c=cmmt.Id;
        insert inDist;
        System.assertNotEquals('MI1test', inDist.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund_Drawdown__c fdDrown=new Fund_Drawdown__c();
        fdDrown.Fund_Name__c=fd.Id;
        insert fdDrown;
        System.assertNotEquals('MI1test', inDist.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('pn','CC');          
        Capital_Call__c cptCall=new Capital_Call__c();
        cptCall.Fund_Drawdown__c=fdDrown.Id;
        cptCall.Commitment__c=cmmt.Id;
        insert cptCall;
        System.assertNotEquals('MI1test', cptCall.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('id',cptCall.id);
        MassEmail_CC_ID MassMl=new MassEmail_CC_ID();
    }
    
    
    static testMethod void mytest2(){        
        String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' AND Name = 'Limited Partner'].Id;
        Organization org=new Organization();
        Account acc = new Account(Name = 'test');
        insert acc;
        System.assertEquals('test', acc.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund__c fd=new Fund__c();
        fd.name='fund';
        fd.Fund_Type__c='fund';
        insert fd;
        System.assertEquals('fund', fd.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('pn','FD');
        Fund_Distribution__c fdDist=new Fund_Distribution__c();
        fdDist.Fund_Name__c=fd.id;
        insert fdDist;
        System.assertNotEquals('test', fdDist.Name); // (PE3.5, SK, 8Aug2017)
           
        apexpages.currentpage().getparameters().put('id',fdDist.id);
        MassEmail_CC_ID MassMl=new MassEmail_CC_ID();
    }
    
    
    static testMethod void mytest3(){        
        String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' AND Name = 'Limited Partner'].Id;
        Organization org=new Organization();
        Account acc = new Account(Name = 'test');
        insert acc;
        System.assertEquals('test', acc.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund__c fd=new Fund__c();
        fd.name='fund';
        fd.Fund_Type__c='fund';
        insert fd;
        System.assertEquals('fund', fd.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund_Distribution__c fdDist=new Fund_Distribution__c();
        fdDist.Fund_Name__c=fd.id;
        insert fdDist; 
        System.assertNotEquals('test', fdDist.Name); // (PE3.5, SK, 8Aug2017)  
        
        Account acc_Lp = new Account();
        acc_Lp.Name='test1';
        // acc_Lp.recordtypeid=recdTypeId;
        acc_Lp.ParentId = acc.Id;
        insert acc_Lp;
        System.assertEquals('test1', acc_Lp.Name); // (PE3.5, SK, 8Aug2017)
        
        Partnership__c ptrship=new Partnership__c();
        ptrship.Name='ravii';
        ptrship.Fund__c=fd.Id;
        insert ptrship;
        System.assertNotEquals('test', ptrship.Name); // (PE3.5, SK, 8Aug2017)
        
        Commitment__c cmmt=new Commitment__c();
        cmmt.Partnership__c=ptrship.Id;
        cmmt.Limited_Partner__c=acc_Lp.id;
        insert cmmt;
        System.assertNotEquals('test', cmmt.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('pn','ID');
        Investor_Distribution__c inDist=new Investor_Distribution__c();
        inDist.Fund_Distribution__c=fdDist.Id;
        inDist.Commitment__c=cmmt.Id;
        insert inDist;
        System.assertNotEquals('test', inDist.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('id',inDist.id);
        MassEmail_CC_ID MassMl=new MassEmail_CC_ID();
    }
    
    
    static testMethod void mytest4(){        
        String recdTypeId = [Select id From RecordType Where SobjectType = 'Account' AND Name = 'Limited Partner'].Id;
        Organization org=new Organization();
        Account acc = new Account(Name = 'test');
        insert acc;
        System.assertEquals('test', acc.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund__c fd=new Fund__c();
        fd.name='fund';
        fd.Fund_Type__c='fund';
        insert fd;
        System.assertEquals('fund', fd.Name); // (PE3.5, SK, 8Aug2017)
        
        Fund_Distribution__c fdDist=new Fund_Distribution__c();
        fdDist.Fund_Name__c=fd.id;
        insert fdDist;   
        System.assertNotEquals('test', fdDist.Name); // (PE3.5, SK, 8Aug2017)
        
        Account acc_Lp = new Account();
        acc_Lp.Name='test1';
        // acc_Lp.recordtypeid=recdTypeId;
        acc_Lp.ParentId = acc.Id;
        insert acc_Lp;
        System.assertEquals('test1', acc_Lp.Name); // (PE3.5, SK, 8Aug2017)
        
        Partnership__c ptrship=new Partnership__c();
        ptrship.Name='ravii';
        ptrship.Fund__c=fd.Id;
        insert ptrship;
        System.assertNotEquals('test', ptrship.Name); // (PE3.5, SK, 8Aug2017)
        
        Commitment__c cmmt=new Commitment__c();
        cmmt.Partnership__c=ptrship.Id;
        cmmt.Limited_Partner__c=acc_Lp.id;
        insert cmmt;
        System.assertNotEquals('test', cmmt.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('pn','ID');
        Investor_Distribution__c inDist=new Investor_Distribution__c();
        inDist.Fund_Distribution__c=fdDist.Id;
        inDist.Commitment__c=cmmt.Id;
        insert inDist;
        System.assertNotEquals('test', inDist.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('id',inDist.id);
        apexpages.currentpage().getparameters().put('pn','DD');
        Fund_Drawdown__c fdDrown=new Fund_Drawdown__c();
        fdDrown.Fund_Name__c=fd.Id;
        insert fdDrown;
        System.assertNotEquals('test', fdDrown.Name); // (PE3.5, SK, 8Aug2017)
        
        apexpages.currentpage().getparameters().put('id',fdDrown.id);
        MassEmail_CC_ID MassMl=new MassEmail_CC_ID();
    }
    
}